
// ==================================================================
// RepackingSessionOriginalDocuments.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SmartProcessing.Server
{


  public class RepackingSessionOriginalDocuments :
    global::Sungero.Domain.ChildEntity, global::Sungero.SmartProcessing.IRepackingSessionOriginalDocuments
  {
    public static new readonly global::System.Guid ClassTypeGuid = global::System.Guid.Parse("35f47ffd-e1c9-4bfa-acfc-8810ab726178");

    public override global::System.Guid TypeGuid
    {
      get { return global::Sungero.SmartProcessing.Server.RepackingSessionOriginalDocuments.ClassTypeGuid; }
    }

    public override string TypeName
    {
      get { return "Sungero.SmartProcessing.IRepackingSessionOriginalDocuments, Sungero.Domain.Interfaces"; }
    }

    public new virtual global::Sungero.SmartProcessing.IRepackingSessionOriginalDocumentsState State
    {
      get { return (global::Sungero.SmartProcessing.IRepackingSessionOriginalDocumentsState)base.State; }
    }

    protected override global::Sungero.Domain.Shared.IEntityState CreateState()
    {
      return new global::Sungero.SmartProcessing.Shared.RepackingSessionOriginalDocumentsState(this);
    }

    public new virtual global::Sungero.SmartProcessing.IRepackingSessionOriginalDocumentsInfo Info
    {
      get { return (global::Sungero.SmartProcessing.IRepackingSessionOriginalDocumentsInfo)base.Info; }
    }


    public global::Sungero.SmartProcessing.IRepackingSession RepackingSession { get; set; }

    public override global::Sungero.Domain.Shared.IEntity RootEntity
    {
      get { return this.RepackingSession; }
      set { this.RepackingSession = (global::Sungero.SmartProcessing.IRepackingSession)value; }
    }

    protected override object CreateSharedHandlers() {
      return new global::Sungero.SmartProcessing.RepackingSessionOriginalDocumentsSharedHandlers(this);
    }

    private global::System.Int64? _DocumentId;
    public virtual global::System.Int64? DocumentId
    {
      get
      {
        return this._DocumentId;
      }

      set
      {
        this.SetPropertyValue("DocumentId", this._DocumentId, value, (propertyValue) => { this._DocumentId = propertyValue; }, this.DocumentIdChangedHandler);
      }
    }
    private global::System.Int32? _VersionNumber;
    public virtual global::System.Int32? VersionNumber
    {
      get
      {
        return this._VersionNumber;
      }

      set
      {
        this.SetPropertyValue("VersionNumber", this._VersionNumber, value, (propertyValue) => { this._VersionNumber = propertyValue; }, this.VersionNumberChangedHandler);
      }
    }
    private global::System.String _DocumentName;
    public virtual global::System.String DocumentName
    {
      get
      {
        return this._DocumentName;
      }

      set
      {
        this.SetPropertyValue("DocumentName", this._DocumentName, value, (propertyValue) => { this._DocumentName = propertyValue; }, this.DocumentNameChangedHandler);
      }
    }
    private global::System.Int32? _ResultVersionNumber;
    public virtual global::System.Int32? ResultVersionNumber
    {
      get
      {
        return this._ResultVersionNumber;
      }

      set
      {
        this.SetPropertyValue("ResultVersionNumber", this._ResultVersionNumber, value, (propertyValue) => { this._ResultVersionNumber = propertyValue; }, this.ResultVersionNumberChangedHandler);
      }
    }










    #region Framework events

    protected void DocumentIdChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.LongIntegerPropertyChangedEventArgs(this.State.Properties.DocumentId, this.DocumentId, this);
     ((global::Sungero.SmartProcessing.IRepackingSessionOriginalDocumentsSharedHandlers)this.SharedHandlers).OriginalDocumentsDocumentIdChanged(args);
    }

    protected void VersionNumberChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.IntegerPropertyChangedEventArgs(this.State.Properties.VersionNumber, this.VersionNumber, this);
     ((global::Sungero.SmartProcessing.IRepackingSessionOriginalDocumentsSharedHandlers)this.SharedHandlers).OriginalDocumentsVersionNumberChanged(args);
    }

    protected void DocumentNameChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.StringPropertyChangedEventArgs(this.State.Properties.DocumentName, this.DocumentName, this);
     ((global::Sungero.SmartProcessing.IRepackingSessionOriginalDocumentsSharedHandlers)this.SharedHandlers).OriginalDocumentsDocumentNameChanged(args);
    }

    protected void ResultVersionNumberChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.IntegerPropertyChangedEventArgs(this.State.Properties.ResultVersionNumber, this.ResultVersionNumber, this);
     ((global::Sungero.SmartProcessing.IRepackingSessionOriginalDocumentsSharedHandlers)this.SharedHandlers).OriginalDocumentsResultVersionNumberChanged(args);
    }



    #endregion


    public RepackingSessionOriginalDocuments()
    {
    }

  }
}

// ==================================================================
// RepackingSessionOriginalDocumentsHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SmartProcessing
{

}

// ==================================================================
// RepackingSessionOriginalDocumentsEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SmartProcessing.Server
{
}
