
// ==================================================================
// ApprovalTaskRevokedDocumentsRights.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Server
{


  public class ApprovalTaskRevokedDocumentsRights :
    global::Sungero.Domain.ChildEntity, global::Sungero.Docflow.IApprovalTaskRevokedDocumentsRights
  {
    public static new readonly global::System.Guid ClassTypeGuid = global::System.Guid.Parse("35cbbafd-281d-4ae4-8840-08a34ee63ba3");

    public override global::System.Guid TypeGuid
    {
      get { return global::Sungero.Docflow.Server.ApprovalTaskRevokedDocumentsRights.ClassTypeGuid; }
    }

    public override string TypeName
    {
      get { return "Sungero.Docflow.IApprovalTaskRevokedDocumentsRights, Sungero.Domain.Interfaces"; }
    }

    public new virtual global::Sungero.Docflow.IApprovalTaskRevokedDocumentsRightsState State
    {
      get { return (global::Sungero.Docflow.IApprovalTaskRevokedDocumentsRightsState)base.State; }
    }

    protected override global::Sungero.Domain.Shared.IEntityState CreateState()
    {
      return new global::Sungero.Docflow.Shared.ApprovalTaskRevokedDocumentsRightsState(this);
    }

    public new virtual global::Sungero.Docflow.IApprovalTaskRevokedDocumentsRightsInfo Info
    {
      get { return (global::Sungero.Docflow.IApprovalTaskRevokedDocumentsRightsInfo)base.Info; }
    }


    public global::Sungero.Docflow.IApprovalTask ApprovalTask { get; set; }

    public override global::Sungero.Domain.Shared.IEntity RootEntity
    {
      get { return this.ApprovalTask; }
      set { this.ApprovalTask = (global::Sungero.Docflow.IApprovalTask)value; }
    }

    protected override object CreateSharedHandlers() {
      return new global::Sungero.Docflow.ApprovalTaskRevokedDocumentsRightsSharedHandlers(this);
    }

    private global::System.Int64? _DocumentId;
    public virtual global::System.Int64? DocumentId
    {
      get
      {
        return this._DocumentId;
      }

      set
      {
        this.SetPropertyValue("DocumentId", this._DocumentId, value, (propertyValue) => { this._DocumentId = propertyValue; }, this.DocumentIdChangedHandler);
      }
    }






    private static global::Sungero.Domain.Shared.EnumerationItems _RightTypeItems = new global::Sungero.Domain.Shared.EnumerationItems(
      null,
      typeof(global::Sungero.Docflow.ApprovalTaskRevokedDocumentsRights.RightType),
      typeof(global::Sungero.Docflow.Server.ApprovalTaskRevokedDocumentsRights),
      "RightType");

    public static global::Sungero.Domain.Shared.EnumerationItems RightTypeItems
    {
      get { return global::Sungero.Docflow.Server.ApprovalTaskRevokedDocumentsRights._RightTypeItems; }
    }

    public virtual global::Sungero.Domain.Shared.EnumerationItems RightTypeAllowedItems
    {
      get { return global::Sungero.Docflow.Server.ApprovalTaskRevokedDocumentsRights.RightTypeItems; }
    }

    private global::Sungero.Core.Enumeration? _RightType;

    public virtual global::Sungero.Core.Enumeration? RightType
    {
      get { return this._RightType; }
      set { this.SetEnumPropertyValue("RightType", this._RightType, value, (propertyValue) => { this._RightType = propertyValue; }, this.RightTypeChangedHandler, this.RightTypeAllowedItems); }
    }





    #region Framework events

    protected void DocumentIdChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.LongIntegerPropertyChangedEventArgs(this.State.Properties.DocumentId, this.DocumentId, this);
     ((global::Sungero.Docflow.IApprovalTaskRevokedDocumentsRightsSharedHandlers)this.SharedHandlers).RevokedDocumentsRightsDocumentIdChanged(args);
    }

    protected void RightTypeChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.EnumerationPropertyChangedEventArgs(this.State.Properties.RightType, this.RightType, this);
     ((global::Sungero.Docflow.IApprovalTaskRevokedDocumentsRightsSharedHandlers)this.SharedHandlers).RevokedDocumentsRightsRightTypeChanged(args);
    }



    #endregion


    public ApprovalTaskRevokedDocumentsRights()
    {
    }

  }
}

// ==================================================================
// ApprovalTaskRevokedDocumentsRightsHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow
{

}

// ==================================================================
// ApprovalTaskRevokedDocumentsRightsEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Server
{
}
