
// ==================================================================
// FreeApprovalTaskState.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Shared
{
  public class FreeApprovalTaskState : 
    global::Sungero.Workflow.Shared.TaskState, global::Sungero.Docflow.IFreeApprovalTaskState
  {
    public FreeApprovalTaskState(global::Sungero.Docflow.IFreeApprovalTask entity) : base(entity) { }

    public new global::Sungero.Docflow.IFreeApprovalTaskPropertyStates Properties
    {
      get { return (global::Sungero.Docflow.IFreeApprovalTaskPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertyStates CreatePropertyStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::Sungero.Docflow.Shared.FreeApprovalTaskPropertyStates(entity);
    }


    public new global::Sungero.Docflow.IFreeApprovalTaskControlStates Controls
    {
      get { return (global::Sungero.Docflow.IFreeApprovalTaskControlStates)base.Controls; }
    }

    protected override global::Sungero.Domain.Shared.IEntityControlStates CreateControlStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::Sungero.Docflow.Shared.FreeApprovalTaskControlStates(entity);
    }

    public new global::Sungero.Docflow.IFreeApprovalTaskPageStates Pages
    {
      get { return (global::Sungero.Docflow.IFreeApprovalTaskPageStates)base.Pages; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPageStates CreatePageStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::Sungero.Docflow.Shared.FreeApprovalTaskPageStates(entity);
    }

    #region Workflow attachments extention

    public global::Sungero.Docflow.IFreeApprovalTaskAttachmentStates Attachments { get { return (global::Sungero.Docflow.IFreeApprovalTaskAttachmentStates)this.AttachmentStates; }}

      protected override global::Sungero.Workflow.Interfaces.IWorkflowEntityAttachmentStates CreateAttachmentStates(global::Sungero.Workflow.Interfaces.IWorkflowEntity entity) 
      {
        return new FreeApprovalTaskAttachmentStates(entity);
      }

    #endregion
  }

  #region Workflow attachments extention

    public class FreeApprovalTaskAttachmentStates :
      global::Sungero.Workflow.Shared.TaskAttachmentStates, global::Sungero.Docflow.IFreeApprovalTaskAttachmentStates
    {
      public global::Sungero.Workflow.Interfaces.IAttachmentGroupState ForApprovalGroup 
      {
        get
        {
          return this.AttachmentGroups.GetAttachmentGroupState(global::System.Guid.Parse("cd77936e-884e-44bb-b869-9a60f9f5f2b4"));
        }
      }
      public global::Sungero.Workflow.Interfaces.IAttachmentGroupState AddendaGroup 
      {
        get
        {
          return this.AttachmentGroups.GetAttachmentGroupState(global::System.Guid.Parse("fe0d933f-02f8-4733-b110-1e49467a9cf8"));
        }
      }
      public global::Sungero.Workflow.Interfaces.IAttachmentGroupState OtherGroup 
      {
        get
        {
          return this.AttachmentGroups.GetAttachmentGroupState(global::System.Guid.Parse("698df64c-b849-4786-ae93-19a1f086a2a8"));
        }
      }


      protected internal FreeApprovalTaskAttachmentStates(global::Sungero.Workflow.Interfaces.IWorkflowEntity entity) : base(entity) { }
    }

  #endregion

  public class FreeApprovalTaskControlStates : 
    global::Sungero.Workflow.Shared.TaskControlStates, global::Sungero.Docflow.IFreeApprovalTaskControlStates
  {

    protected internal FreeApprovalTaskControlStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }
  public class FreeApprovalTaskPageStates : 
    global::Sungero.Workflow.Shared.TaskPageStates, global::Sungero.Docflow.IFreeApprovalTaskPageStates
  {

    protected internal FreeApprovalTaskPageStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

  public class FreeApprovalTaskPropertyStates : 
    global::Sungero.Workflow.Shared.TaskPropertyStates, global::Sungero.Docflow.IFreeApprovalTaskPropertyStates
  {
            public new global::Sungero.Docflow.IFreeApprovalTaskObserversCollectionPropertyState<global::Sungero.Docflow.IFreeApprovalTaskObservers> Observers
            {
              get { return (global::Sungero.Docflow.IFreeApprovalTaskObserversCollectionPropertyState<global::Sungero.Docflow.IFreeApprovalTaskObservers>)base.Observers; }
            }

            protected override global::Sungero.Workflow.ITaskObserversCollectionPropertyState<global::Sungero.Workflow.ITaskObservers> CreateObserversState(global::Sungero.Domain.Shared.IEntity entity, string propertyName)
            {
              return new global::Sungero.Docflow.Shared.FreeApprovalTaskObserversCollectionPropertyState<global::Sungero.Docflow.IFreeApprovalTaskObservers>(entity, propertyName);
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::System.Boolean?> ReceiveNotice 
            {
              get { return this.GetPropertyState<global::System.Boolean?>("ReceiveNotice"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Core.Enumeration?> ReceiveOnCompletion 
            {
              get { return this.GetPropertyState<global::Sungero.Core.Enumeration?>("ReceiveOnCompletion"); }
            }
            public global::Sungero.Docflow.IFreeApprovalTaskApproversCollectionPropertyState<global::Sungero.Docflow.IFreeApprovalTaskApprovers> Approvers 
            {
              get { return this.GetPropertyState("Approvers", this.CreateApproversState); }
            }

            protected virtual global::Sungero.Docflow.IFreeApprovalTaskApproversCollectionPropertyState<global::Sungero.Docflow.IFreeApprovalTaskApprovers> CreateApproversState(global::Sungero.Domain.Shared.IEntity entity, string propertyName)
            {
              return new global::Sungero.Docflow.Shared.FreeApprovalTaskApproversCollectionPropertyState<global::Sungero.Docflow.IFreeApprovalTaskApprovers>(entity, propertyName);
            }
            public global::Sungero.Docflow.IFreeApprovalTaskAddedAddendaCollectionPropertyState<global::Sungero.Docflow.IFreeApprovalTaskAddedAddenda> AddedAddenda 
            {
              get { return this.GetPropertyState("AddedAddenda", this.CreateAddedAddendaState); }
            }

            protected virtual global::Sungero.Docflow.IFreeApprovalTaskAddedAddendaCollectionPropertyState<global::Sungero.Docflow.IFreeApprovalTaskAddedAddenda> CreateAddedAddendaState(global::Sungero.Domain.Shared.IEntity entity, string propertyName)
            {
              return new global::Sungero.Docflow.Shared.FreeApprovalTaskAddedAddendaCollectionPropertyState<global::Sungero.Docflow.IFreeApprovalTaskAddedAddenda>(entity, propertyName);
            }
            public global::Sungero.Docflow.IFreeApprovalTaskRemovedAddendaCollectionPropertyState<global::Sungero.Docflow.IFreeApprovalTaskRemovedAddenda> RemovedAddenda 
            {
              get { return this.GetPropertyState("RemovedAddenda", this.CreateRemovedAddendaState); }
            }

            protected virtual global::Sungero.Docflow.IFreeApprovalTaskRemovedAddendaCollectionPropertyState<global::Sungero.Docflow.IFreeApprovalTaskRemovedAddenda> CreateRemovedAddendaState(global::Sungero.Domain.Shared.IEntity entity, string propertyName)
            {
              return new global::Sungero.Docflow.Shared.FreeApprovalTaskRemovedAddendaCollectionPropertyState<global::Sungero.Docflow.IFreeApprovalTaskRemovedAddenda>(entity, propertyName);
            }


    protected internal FreeApprovalTaskPropertyStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

}

// ==================================================================
// FreeApprovalTaskInfo.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Shared
{
  public class FreeApprovalTaskInfo : 
    global::Sungero.Workflow.Shared.TaskInfo, global::Sungero.Docflow.IFreeApprovalTaskInfo
  {
    public FreeApprovalTaskInfo(global::System.Type entityType) : base(entityType) { }

    public new global::Sungero.Docflow.IFreeApprovalTaskPropertiesInfo Properties
    {
      get { return (global::Sungero.Docflow.IFreeApprovalTaskPropertiesInfo)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertiesInfo CreateEntityPropertiesInfo(global::System.Type entityType)
    {
      return new global::Sungero.Docflow.Shared.FreeApprovalTaskPropertiesInfo(entityType);
    }

  }

  public class FreeApprovalTaskPropertiesInfo : 
    global::Sungero.Workflow.Shared.TaskPropertiesInfo, global::Sungero.Docflow.IFreeApprovalTaskPropertiesInfo
  {
        public new global::Sungero.Domain.Shared.ICollectionPropertyInfo<global::Sungero.Docflow.IFreeApprovalTaskObserversPropertiesInfo> Observers
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.CollectionPropertyMetadata>("Observers");
             return new global::Sungero.Domain.Shared.CollectionPropertyInfo<global::Sungero.Docflow.IFreeApprovalTaskObserversPropertiesInfo>(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.IBooleanPropertyInfo ReceiveNotice 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.BooleanPropertyMetadata>("ReceiveNotice");
             return new global::Sungero.Domain.Shared.BooleanPropertyInfo(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.IEnumPropertyInfo ReceiveOnCompletion 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.EnumPropertyMetadata>("ReceiveOnCompletion");
             return new global::Sungero.Domain.Shared.EnumPropertyInfo(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.ICollectionPropertyInfo<global::Sungero.Docflow.IFreeApprovalTaskApproversPropertiesInfo> Approvers 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.CollectionPropertyMetadata>("Approvers");
             return new global::Sungero.Domain.Shared.CollectionPropertyInfo<global::Sungero.Docflow.IFreeApprovalTaskApproversPropertiesInfo>(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.ICollectionPropertyInfo<global::Sungero.Docflow.IFreeApprovalTaskAddedAddendaPropertiesInfo> AddedAddenda 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.CollectionPropertyMetadata>("AddedAddenda");
             return new global::Sungero.Domain.Shared.CollectionPropertyInfo<global::Sungero.Docflow.IFreeApprovalTaskAddedAddendaPropertiesInfo>(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.ICollectionPropertyInfo<global::Sungero.Docflow.IFreeApprovalTaskRemovedAddendaPropertiesInfo> RemovedAddenda 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.CollectionPropertyMetadata>("RemovedAddenda");
             return new global::Sungero.Domain.Shared.CollectionPropertyInfo<global::Sungero.Docflow.IFreeApprovalTaskRemovedAddendaPropertiesInfo>(propertyMetadata);
          }
        }


    protected internal FreeApprovalTaskPropertiesInfo(global::System.Type entityType) : base(entityType) { }
  }

}

// ==================================================================
// FreeApprovalTaskHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow
{
  public partial class FreeApprovalTaskSharedHandlers : global::Sungero.Workflow.TaskSharedHandlers, IFreeApprovalTaskSharedHandlers
  {
    private global::Sungero.Docflow.IFreeApprovalTask _obj
    {
      get { return (global::Sungero.Docflow.IFreeApprovalTask)this.Entity; }
    }
    public virtual void ReceiveNoticeChanged(global::Sungero.Domain.Shared.BooleanPropertyChangedEventArgs e) { }


    public virtual void ReceiveOnCompletionChanged(global::Sungero.Domain.Shared.EnumerationPropertyChangedEventArgs e) { }


    public virtual void ApproversChanged(global::Sungero.Domain.Shared.CollectionPropertyChangedEventArgs e) { }


    public virtual void AddedAddendaChanged(global::Sungero.Domain.Shared.CollectionPropertyChangedEventArgs e) { }


    public virtual void RemovedAddendaChanged(global::Sungero.Domain.Shared.CollectionPropertyChangedEventArgs e) { }



    #region Workflow attachments extention

        public virtual void ForApprovalGroupCreated(global::Sungero.Workflow.Interfaces.AttachmentCreatedEventArgs e) { }


        public virtual void OtherGroupCreated(global::Sungero.Workflow.Interfaces.AttachmentCreatedEventArgs e) { }
        public virtual void OtherGroupAdded(global::Sungero.Workflow.Interfaces.AttachmentAddedEventArgs e) { }
        public virtual void OtherGroupDeleted(global::Sungero.Workflow.Interfaces.AttachmentDeletedEventArgs e) { }


    #endregion

    public FreeApprovalTaskSharedHandlers(global::Sungero.Docflow.IFreeApprovalTask entity) : base(entity)
    {
    }
  }

  public partial class FreeApprovalTaskApproversSharedHandlers : global::Sungero.Domain.Shared.ChildEntitySharedHandlers, IFreeApprovalTaskApproversSharedHandlers
  {
    private global::Sungero.Docflow.IFreeApprovalTaskApprovers _obj
    {
      get { return (global::Sungero.Docflow.IFreeApprovalTaskApprovers)this.Entity; }
    }
    public virtual void ApproversApproverChanged(global::Sungero.Docflow.Shared.FreeApprovalTaskApproversApproverChangedEventArgs e) { }



    public FreeApprovalTaskApproversSharedHandlers(global::Sungero.Docflow.IFreeApprovalTaskApprovers entity) : base(entity)
    {
    }
  }

  public partial class FreeApprovalTaskApproversSharedCollectionHandlers : global::Sungero.Domain.Shared.ChildEntitySharedCollectionHandlers
  {
    private global::Sungero.Docflow.IFreeApprovalTask _obj
    { 
      get { return (global::Sungero.Docflow.IFreeApprovalTask)this.Entity; }
    }

    private global::Sungero.Docflow.IFreeApprovalTaskApprovers _added
    {
      get { return (global::Sungero.Docflow.IFreeApprovalTaskApprovers)this._Added; }
    }

    private global::Sungero.Docflow.IFreeApprovalTaskApprovers _deleted
    {
      get { return (global::Sungero.Docflow.IFreeApprovalTaskApprovers)this._Deleted; }
    }

    private global::Sungero.Docflow.IFreeApprovalTaskApprovers _source
    {
      get { return (global::Sungero.Docflow.IFreeApprovalTaskApprovers)this._Source; }
    }

    public virtual void ApproversAdded(global::Sungero.Domain.Shared.CollectionPropertyAddedEventArgs e) { }
    public virtual void ApproversDeleted(global::Sungero.Domain.Shared.CollectionPropertyDeletedEventArgs e) { }

    public FreeApprovalTaskApproversSharedCollectionHandlers(global::Sungero.Docflow.IFreeApprovalTask entity, global::Sungero.Domain.Shared.IChildEntity added, global::Sungero.Domain.Shared.IChildEntity deleted, global::Sungero.Domain.Shared.IChildEntity source)
      : base (entity, added, deleted, source)
    {
    }
  }

  public partial class FreeApprovalTaskAddedAddendaSharedHandlers : global::Sungero.Domain.Shared.ChildEntitySharedHandlers, IFreeApprovalTaskAddedAddendaSharedHandlers
  {
    private global::Sungero.Docflow.IFreeApprovalTaskAddedAddenda _obj
    {
      get { return (global::Sungero.Docflow.IFreeApprovalTaskAddedAddenda)this.Entity; }
    }
    public virtual void AddedAddendaAddendumIdChanged(global::Sungero.Domain.Shared.LongIntegerPropertyChangedEventArgs e) { }



    public FreeApprovalTaskAddedAddendaSharedHandlers(global::Sungero.Docflow.IFreeApprovalTaskAddedAddenda entity) : base(entity)
    {
    }
  }

  public partial class FreeApprovalTaskAddedAddendaSharedCollectionHandlers : global::Sungero.Domain.Shared.ChildEntitySharedCollectionHandlers
  {
    private global::Sungero.Docflow.IFreeApprovalTask _obj
    { 
      get { return (global::Sungero.Docflow.IFreeApprovalTask)this.Entity; }
    }

    private global::Sungero.Docflow.IFreeApprovalTaskAddedAddenda _added
    {
      get { return (global::Sungero.Docflow.IFreeApprovalTaskAddedAddenda)this._Added; }
    }

    private global::Sungero.Docflow.IFreeApprovalTaskAddedAddenda _deleted
    {
      get { return (global::Sungero.Docflow.IFreeApprovalTaskAddedAddenda)this._Deleted; }
    }

    private global::Sungero.Docflow.IFreeApprovalTaskAddedAddenda _source
    {
      get { return (global::Sungero.Docflow.IFreeApprovalTaskAddedAddenda)this._Source; }
    }

    public virtual void AddedAddendaAdded(global::Sungero.Domain.Shared.CollectionPropertyAddedEventArgs e) { }
    public virtual void AddedAddendaDeleted(global::Sungero.Domain.Shared.CollectionPropertyDeletedEventArgs e) { }

    public FreeApprovalTaskAddedAddendaSharedCollectionHandlers(global::Sungero.Docflow.IFreeApprovalTask entity, global::Sungero.Domain.Shared.IChildEntity added, global::Sungero.Domain.Shared.IChildEntity deleted, global::Sungero.Domain.Shared.IChildEntity source)
      : base (entity, added, deleted, source)
    {
    }
  }

  public partial class FreeApprovalTaskRemovedAddendaSharedHandlers : global::Sungero.Domain.Shared.ChildEntitySharedHandlers, IFreeApprovalTaskRemovedAddendaSharedHandlers
  {
    private global::Sungero.Docflow.IFreeApprovalTaskRemovedAddenda _obj
    {
      get { return (global::Sungero.Docflow.IFreeApprovalTaskRemovedAddenda)this.Entity; }
    }
    public virtual void RemovedAddendaAddendumIdChanged(global::Sungero.Domain.Shared.LongIntegerPropertyChangedEventArgs e) { }



    public FreeApprovalTaskRemovedAddendaSharedHandlers(global::Sungero.Docflow.IFreeApprovalTaskRemovedAddenda entity) : base(entity)
    {
    }
  }

  public partial class FreeApprovalTaskRemovedAddendaSharedCollectionHandlers : global::Sungero.Domain.Shared.ChildEntitySharedCollectionHandlers
  {
    private global::Sungero.Docflow.IFreeApprovalTask _obj
    { 
      get { return (global::Sungero.Docflow.IFreeApprovalTask)this.Entity; }
    }

    private global::Sungero.Docflow.IFreeApprovalTaskRemovedAddenda _added
    {
      get { return (global::Sungero.Docflow.IFreeApprovalTaskRemovedAddenda)this._Added; }
    }

    private global::Sungero.Docflow.IFreeApprovalTaskRemovedAddenda _deleted
    {
      get { return (global::Sungero.Docflow.IFreeApprovalTaskRemovedAddenda)this._Deleted; }
    }

    private global::Sungero.Docflow.IFreeApprovalTaskRemovedAddenda _source
    {
      get { return (global::Sungero.Docflow.IFreeApprovalTaskRemovedAddenda)this._Source; }
    }

    public virtual void RemovedAddendaAdded(global::Sungero.Domain.Shared.CollectionPropertyAddedEventArgs e) { }
    public virtual void RemovedAddendaDeleted(global::Sungero.Domain.Shared.CollectionPropertyDeletedEventArgs e) { }

    public FreeApprovalTaskRemovedAddendaSharedCollectionHandlers(global::Sungero.Docflow.IFreeApprovalTask entity, global::Sungero.Domain.Shared.IChildEntity added, global::Sungero.Domain.Shared.IChildEntity deleted, global::Sungero.Domain.Shared.IChildEntity source)
      : base (entity, added, deleted, source)
    {
    }
  }

}

// ==================================================================
// FreeApprovalTaskResources.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Shared.FreeApprovalTask
{
  /// <summary>
  /// Represents FreeApprovalTask resources.
  /// </summary>
  public class FreeApprovalTaskResources : global::Sungero.Workflow.Shared.Task.TaskResources, global::Sungero.Docflow.FreeApprovalTask.IFreeApprovalTaskResources
  {
    public virtual global::CommonLibrary.LocalizedString NeedTextForRework
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask) , "NeedTextForRework");
      }
    }

    public virtual global::CommonLibrary.LocalizedString NeedTextForReworkFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask), "NeedTextForRework", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString CantSendDocumentsWithoutUpdateRights
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask) , "CantSendDocumentsWithoutUpdateRights");
      }
    }

    public virtual global::CommonLibrary.LocalizedString CantSendDocumentsWithoutUpdateRightsFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask), "CantSendDocumentsWithoutUpdateRights", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString ApproversAsgSubject
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask) , "ApproversAsgSubject");
      }
    }

    public virtual global::CommonLibrary.LocalizedString ApproversAsgSubjectFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask), "ApproversAsgSubject", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString RevisionAsgSubject
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask) , "RevisionAsgSubject");
      }
    }

    public virtual global::CommonLibrary.LocalizedString RevisionAsgSubjectFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask), "RevisionAsgSubject", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString TaskSubject
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask) , "TaskSubject");
      }
    }

    public virtual global::CommonLibrary.LocalizedString TaskSubjectFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask), "TaskSubject", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString ApprovalCompletedSubject
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask) , "ApprovalCompletedSubject");
      }
    }

    public virtual global::CommonLibrary.LocalizedString ApprovalCompletedSubjectFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask), "ApprovalCompletedSubject", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString NewApprovalLapSubject
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask) , "NewApprovalLapSubject");
      }
    }

    public virtual global::CommonLibrary.LocalizedString NewApprovalLapSubjectFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask), "NewApprovalLapSubject", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString ReworkNoticeSubject
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask) , "ReworkNoticeSubject");
      }
    }

    public virtual global::CommonLibrary.LocalizedString ReworkNoticeSubjectFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask), "ReworkNoticeSubject", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString ImpossibleSpecifyDeadlineLessThanToday
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask) , "ImpossibleSpecifyDeadlineLessThanToday");
      }
    }

    public virtual global::CommonLibrary.LocalizedString ImpossibleSpecifyDeadlineLessThanTodayFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask), "ImpossibleSpecifyDeadlineLessThanToday", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString ApprovalText
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask) , "ApprovalText");
      }
    }

    public virtual global::CommonLibrary.LocalizedString ApprovalTextFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask), "ApprovalText", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString Approved
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask) , "Approved");
      }
    }

    public virtual global::CommonLibrary.LocalizedString ApprovedFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask), "Approved", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString ForRework
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask) , "ForRework");
      }
    }

    public virtual global::CommonLibrary.LocalizedString ForReworkFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask), "ForRework", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString ForReapproving
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask) , "ForReapproving");
      }
    }

    public virtual global::CommonLibrary.LocalizedString ForReapprovingFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask), "ForReapproving", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString AbortApproving
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask) , "AbortApproving");
      }
    }

    public virtual global::CommonLibrary.LocalizedString AbortApprovingFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask), "AbortApproving", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString StateViewFreeApproval
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask) , "StateViewFreeApproval");
      }
    }

    public virtual global::CommonLibrary.LocalizedString StateViewFreeApprovalFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask), "StateViewFreeApproval", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString StateViewCompleteApprovalAssignment
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask) , "StateViewCompleteApprovalAssignment");
      }
    }

    public virtual global::CommonLibrary.LocalizedString StateViewCompleteApprovalAssignmentFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask), "StateViewCompleteApprovalAssignment", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString StateViewReworkByRemarks
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask) , "StateViewReworkByRemarks");
      }
    }

    public virtual global::CommonLibrary.LocalizedString StateViewReworkByRemarksFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask), "StateViewReworkByRemarks", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString Forwarded
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask) , "Forwarded");
      }
    }

    public virtual global::CommonLibrary.LocalizedString ForwardedFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask), "Forwarded", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString AddApprover
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask) , "AddApprover");
      }
    }

    public virtual global::CommonLibrary.LocalizedString AddApproverFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask), "AddApprover", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString CantRedirectWithoutAddressee
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask) , "CantRedirectWithoutAddressee");
      }
    }

    public virtual global::CommonLibrary.LocalizedString CantRedirectWithoutAddresseeFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask), "CantRedirectWithoutAddressee", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString Approver
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask) , "Approver");
      }
    }

    public virtual global::CommonLibrary.LocalizedString ApproverFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask), "Approver", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString Add
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask) , "Add");
      }
    }

    public virtual global::CommonLibrary.LocalizedString AddFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask), "Add", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString SendedTo
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask) , "SendedTo");
      }
    }

    public virtual global::CommonLibrary.LocalizedString SendedToFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask), "SendedTo", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString AddApproverDeadline
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask) , "AddApproverDeadline");
      }
    }

    public virtual global::CommonLibrary.LocalizedString AddApproverDeadlineFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IFreeApprovalTask), "AddApproverDeadline", false, args);
    }

    public virtual global::System.String FreeApproveStage
    {
      get
      {
        return "resource://77f43035-9f23-4a19-9882-5a6a2cd5c9c7;FreeApproveStage";
      }
    }
    public virtual global::System.String Forward
    {
      get
      {
        return "resource://77f43035-9f23-4a19-9882-5a6a2cd5c9c7;Forward";
      }
    }

  }
}

// ==================================================================
// FreeApprovalTaskSharedFunctions.g.cs
// ==================================================================

namespace Sungero.Docflow.Shared
{
  public partial class FreeApprovalTaskFunctions : global::Sungero.Workflow.Shared.TaskFunctions
  {
    private global::Sungero.Docflow.IFreeApprovalTask _obj
    {
      get { return (global::Sungero.Docflow.IFreeApprovalTask)this.Entity; }
    }

    public FreeApprovalTaskFunctions(global::Sungero.Docflow.IFreeApprovalTask entity) : base(entity) { }
  }
}

// ==================================================================
// FreeApprovalTaskFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Functions
{
  internal static class FreeApprovalTask
  {
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FreeApprovalTaskFunctions" />
    internal static  global::System.Collections.Generic.List<global::Sungero.Docflow.Structures.FreeApprovalTask.StartValidationMessage> GetStartValidationMessages(global::Sungero.Docflow.IFreeApprovalTask freeApprovalTask)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)freeApprovalTask).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetStartValidationMessages", new System.Type[] {  });
      return (global::System.Collections.Generic.List<global::Sungero.Docflow.Structures.FreeApprovalTask.StartValidationMessage>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FreeApprovalTaskFunctions" />
    internal static  global::System.Boolean ValidateFreeApprovalTaskStart(global::Sungero.Docflow.IFreeApprovalTask freeApprovalTask, Sungero.Core.IValidationArgs e)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)freeApprovalTask).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("ValidateFreeApprovalTaskStart", new System.Type[] { typeof(Sungero.Core.IValidationArgs) });
      return (global::System.Boolean)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { e });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FreeApprovalTaskFunctions" />
    internal static  void SynchronizeAddendaAndAttachmentsGroup(global::Sungero.Docflow.IFreeApprovalTask freeApprovalTask)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)freeApprovalTask).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("SynchronizeAddendaAndAttachmentsGroup", new System.Type[] {  });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FreeApprovalTaskFunctions" />
    internal static  void AddedAddendaAppend(global::Sungero.Docflow.IFreeApprovalTask freeApprovalTask)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)freeApprovalTask).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("AddedAddendaAppend", new System.Type[] {  });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FreeApprovalTaskFunctions" />
    internal static  void RemovedAddendaAppend(global::Sungero.Docflow.IFreeApprovalTask freeApprovalTask)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)freeApprovalTask).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("RemovedAddendaAppend", new System.Type[] {  });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FreeApprovalTaskFunctions" />
    internal static  void AddedAddendaAppend(global::Sungero.Docflow.IFreeApprovalTask freeApprovalTask, global::Sungero.Content.IElectronicDocument addendum)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)freeApprovalTask).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("AddedAddendaAppend", new System.Type[] { typeof(global::Sungero.Content.IElectronicDocument) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { addendum });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FreeApprovalTaskFunctions" />
    internal static  void AddedAddendaRemove(global::Sungero.Docflow.IFreeApprovalTask freeApprovalTask, global::Sungero.Content.IElectronicDocument addendum)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)freeApprovalTask).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("AddedAddendaRemove", new System.Type[] { typeof(global::Sungero.Content.IElectronicDocument) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { addendum });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FreeApprovalTaskFunctions" />
    internal static  void RemovedAddendaAppend(global::Sungero.Docflow.IFreeApprovalTask freeApprovalTask, global::Sungero.Content.IElectronicDocument addendum)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)freeApprovalTask).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("RemovedAddendaAppend", new System.Type[] { typeof(global::Sungero.Content.IElectronicDocument) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { addendum });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FreeApprovalTaskFunctions" />
    internal static  void RemovedAddendaRemove(global::Sungero.Docflow.IFreeApprovalTask freeApprovalTask, global::Sungero.Content.IElectronicDocument addendum)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)freeApprovalTask).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("RemovedAddendaRemove", new System.Type[] { typeof(global::Sungero.Content.IElectronicDocument) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { addendum });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FreeApprovalTaskFunctions" />
    internal static  global::System.Collections.Generic.List<global::Sungero.Content.IElectronicDocument> GetAddendaGroupAttachments(global::Sungero.Docflow.IFreeApprovalTask freeApprovalTask)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)freeApprovalTask).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetAddendaGroupAttachments", new System.Type[] {  });
      return (global::System.Collections.Generic.List<global::Sungero.Content.IElectronicDocument>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FreeApprovalTaskFunctions" />
    internal static  global::System.Collections.Generic.List<global::System.Int64> GetAddedAddenda(global::Sungero.Docflow.IFreeApprovalTask freeApprovalTask)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)freeApprovalTask).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetAddedAddenda", new System.Type[] {  });
      return (global::System.Collections.Generic.List<global::System.Int64>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FreeApprovalTaskFunctions" />
    internal static  global::System.Collections.Generic.List<global::System.Int64> GetRemovedAddenda(global::Sungero.Docflow.IFreeApprovalTask freeApprovalTask)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)freeApprovalTask).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetRemovedAddenda", new System.Type[] {  });
      return (global::System.Collections.Generic.List<global::System.Int64>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FreeApprovalTaskFunctions" />
    internal static  global::System.Collections.Generic.List<global::Sungero.Content.IElectronicDocument> GetAddedAddendaFromAssignments(global::Sungero.Docflow.IFreeApprovalTask freeApprovalTask)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)freeApprovalTask).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetAddedAddendaFromAssignments", new System.Type[] {  });
      return (global::System.Collections.Generic.List<global::Sungero.Content.IElectronicDocument>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FreeApprovalTaskFunctions" />
    internal static  global::System.Collections.Generic.List<global::Sungero.Content.IElectronicDocument> GetRemovedAddendaFromAssignments(global::Sungero.Docflow.IFreeApprovalTask freeApprovalTask)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)freeApprovalTask).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetRemovedAddendaFromAssignments", new System.Type[] {  });
      return (global::System.Collections.Generic.List<global::Sungero.Content.IElectronicDocument>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.Docflow.Shared" type="Sungero.Docflow.Shared.FreeApprovalTaskFunctions" />
    internal static  global::System.Boolean HasDocumentAndCanRead(global::Sungero.Docflow.IFreeApprovalTask freeApprovalTask)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)freeApprovalTask).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("HasDocumentAndCanRead", new System.Type[] {  });
      return (global::System.Boolean)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }

    internal static class Remote
    {
      /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FreeApprovalTaskFunctions" />
      internal static global::System.String  GetStateView(global::Sungero.Docflow.IFreeApprovalTask freeApprovalTask)
      {
        return global::Sungero.Domain.Shared.RemoteFunctionExecutor.ExecuteWithResult<global::System.String>(
          global::System.Guid.Parse("77f43035-9f23-4a19-9882-5a6a2cd5c9c7"),
          "GetStateView(global::Sungero.Docflow.IFreeApprovalTask)"
          , freeApprovalTask);
      }
      /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.FreeApprovalTaskFunctions" />
      internal static  global::Sungero.Docflow.Structures.Module.AttachmentHistoryEntries GetAttachmentHistoryEntriesByGroupId(global::Sungero.Docflow.IFreeApprovalTask freeApprovalTask, global::System.Guid groupId)
      {
        return global::Sungero.Domain.Shared.RemoteFunctionExecutor.ExecuteWithResult<global::Sungero.Docflow.Structures.Module.AttachmentHistoryEntries>(
          global::System.Guid.Parse("77f43035-9f23-4a19-9882-5a6a2cd5c9c7"),
          "GetAttachmentHistoryEntriesByGroupId(global::Sungero.Docflow.IFreeApprovalTask,global::System.Guid)"
          , freeApprovalTask, groupId);
      }

    }
  }
}

// ==================================================================
// FreeApprovalTaskFilterState.g.cs
// ==================================================================

namespace Sungero.Docflow.Shared.FreeApprovalTask
{

  public class FreeApprovalTaskFilterInfo : global::Sungero.Workflow.Shared.Task.TaskFilterInfo,
    global::Sungero.Docflow.IFreeApprovalTaskFilterInfo
  {
  }

  public class FreeApprovalTaskFilterState : global::Sungero.Workflow.Shared.Task.TaskFilterState,
    global::Sungero.Docflow.IFreeApprovalTaskFilterState
  {



    public new Sungero.Docflow.IFreeApprovalTaskFilterInfo Info
    {
      get
      {
        return (Sungero.Docflow.IFreeApprovalTaskFilterInfo) base.Info;
      }
    }
    protected override global::Sungero.Domain.Shared.IFilterInfo CreateFilterInfo()
    {
      return new Sungero.Docflow.Shared.FreeApprovalTask.FreeApprovalTaskFilterInfo();
    }

  }
}

// ==================================================================
// FreeApprovalTaskSharedPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Shared
{
  public class FreeApprovalTaskSharedPublicFunctions : global::Sungero.Docflow.Shared.IFreeApprovalTaskSharedPublicFunctions
  {
  }
}

// ==================================================================
// FreeApprovalTaskAttachmentGroups.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Shared
{

  public class FreeApprovalTaskForApprovalGroupAttachments : global::Sungero.Workflow.Shared.WorkflowEntityAttachmentGroupDecorator,
    global::Sungero.Docflow.IFreeApprovalTaskForApprovalGroupAttachments
  {
      public global::System.Collections.Generic.ICollection<global::Sungero.Content.IElectronicDocument> ElectronicDocuments
      { 
        get 
        { 
          return this.GetAttachmentGroupCollection<global::Sungero.Content.IElectronicDocument>();
        } 
      }


    public FreeApprovalTaskForApprovalGroupAttachments(global::Sungero.Workflow.Interfaces.IWorkflowEntity entity) : base(entity, "cd77936e-884e-44bb-b869-9a60f9f5f2b4") { }
  }

  public class FreeApprovalTaskAddendaGroupAttachments : global::Sungero.Workflow.Shared.WorkflowEntityAttachmentGroupDecorator,
    global::Sungero.Docflow.IFreeApprovalTaskAddendaGroupAttachments
  {
      public global::System.Collections.Generic.ICollection<global::Sungero.Content.IElectronicDocument> ElectronicDocuments
      { 
        get 
        { 
          return this.GetAttachmentGroupCollection<global::Sungero.Content.IElectronicDocument>();
        } 
      }


    public FreeApprovalTaskAddendaGroupAttachments(global::Sungero.Workflow.Interfaces.IWorkflowEntity entity) : base(entity, "fe0d933f-02f8-4733-b110-1e49467a9cf8") { }
  }

  public class FreeApprovalTaskOtherGroupAttachments : global::Sungero.Workflow.Shared.WorkflowEntityAttachmentGroupDecorator,
    global::Sungero.Docflow.IFreeApprovalTaskOtherGroupAttachments
  {

    public FreeApprovalTaskOtherGroupAttachments(global::Sungero.Workflow.Interfaces.IWorkflowEntity entity) : base(entity, "698df64c-b849-4786-ae93-19a1f086a2a8") { }
  }

}

// ==================================================================
// FreeApprovalTaskExtendedSchemeVersions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.FreeApprovalTask
{

    /// <summary>
    /// Список версий схемы.
    /// </summary>
    public static class LayerSchemeVersions
    {
      public static readonly global::Sungero.Workflow.Shared.ExtendedSchemeVersion V1 =
        new global::Sungero.Workflow.Shared.ExtendedSchemeVersion(1, global::System.Guid.Parse("0745199f-eaac-4875-8563-40ed1e5ce317"));
      public static readonly global::Sungero.Workflow.Shared.ExtendedSchemeVersion V2 =
        new global::Sungero.Workflow.Shared.ExtendedSchemeVersion(2, global::System.Guid.Parse("7ce6852c-2346-4ea5-86d4-bdac0b1902d0"));
      public static readonly global::Sungero.Workflow.Shared.ExtendedSchemeVersion V3 =
        new global::Sungero.Workflow.Shared.ExtendedSchemeVersion(3, global::System.Guid.Parse("b87fbd2e-278a-439c-a10a-716de8bd84bf"));
}

    public static class TaskExtensions
    {
      /// <summary>
      /// Получить версию схемы запущенной задачи.
      /// </summary>
      /// <param name="task">Задача.</param>
      /// <returns>Версия схемы запущенной задачи.</returns>
      public static global::Sungero.Workflow.Shared.ExtendedSchemeVersion GetStartedSchemeVersion(this global::Sungero.Workflow.ITask task)
      {
        return global::Sungero.Workflow.Shared.OverriddenTaskHelper.FindLayerSchemeVersionForTask(task,
          global::System.Guid.Parse("77f43035-9f23-4a19-9882-5a6a2cd5c9c7"));
      }
    }

}
