
// ==================================================================
// MobileAppSetting.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.MobileApps.Server
{
    public class MobileAppSettingFilter<T> :
      global::Sungero.Domain.EntityFilterBase<T>
      where T : class, global::Sungero.MobileApps.IMobileAppSetting
    {
      protected new global::Sungero.MobileApps.IMobileAppSettingFilterState Filter { get; private set; }

      private global::Sungero.MobileApps.IMobileAppSettingFilterState filter
      {
        get
        {
          return this.Filter;
        }
      }

      protected override global::System.Linq.IQueryable<T> ApplyAppliedFilter(global::System.Linq.IQueryable<T> query)
      {
        return base.ApplyAppliedFilter(query);
      }

      public MobileAppSettingFilter(global::Sungero.MobileApps.IMobileAppSettingFilterState filter)
      : base()
      {
        this.Filter = filter;
      }

      protected MobileAppSettingFilter()
      {
      }
    }
      public class MobileAppSettingUiFilter<T> :
        global::Sungero.Domain.EntityUiFilterBase<T>
        where T : class, global::Sungero.MobileApps.IMobileAppSetting
      {
        protected override global::System.Linq.IQueryable<T> ApplyAppliedFilter(global::System.Linq.IQueryable<T> query)
        {
          return base.ApplyAppliedFilter(query);
        }
      }

    public class MobileAppSettingSearchDialogModel : global::Sungero.CoreEntities.Server.DatabookEntrySearchDialogModel
        {
                  public override global::System.Int64? Id { get; protected set; }




                  public virtual global::System.Collections.Generic.IEnumerable<Sungero.CoreEntities.IRecipient> Employee { get; protected set; }


                   [Sungero.Domain.Shared.HideInDevStudio()]
                   public MobileAppSettingVisibleFoldersModel VisibleFolders { get; protected set; }

        }


      public class MobileAppSettingVisibleFoldersModel : global::Sungero.Domain.CollectionPropertySearchDialogModel
          {
            public override global::System.Int64? Id { get; protected set; }


         }



  public class MobileAppSettingFilterForEmployee<TQueryEntity, TSourceEntity>
    : global::Sungero.Domain.EntityPropertyFilterBase<TQueryEntity, TSourceEntity>
    where TQueryEntity : class, global::Sungero.Company.IEmployee
    where TSourceEntity : class, global::Sungero.MobileApps.IMobileAppSetting
  {
    protected override global::System.Linq.IQueryable<TQueryEntity> ApplyAppliedFilter(global::System.Linq.IQueryable<TQueryEntity> query, TSourceEntity sourceEntity)
    {
      var args = new global::Sungero.Domain.PropertyFilteringEventArgs(sourceEntity);
      global::System.Linq.IQueryable<TQueryEntity> result;
      var filterType = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve("Sungero.MobileApps.MobileAppSettingEmployeePropertyFilteringServerHandler`1");
      if (filterType != null)
      {
        var genericType = filterType.MakeGenericType(typeof(TQueryEntity));
        var instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(genericType, new object[] { sourceEntity });
        var methodInfo = genericType.GetMethod("EmployeeFiltering");
        result = (global::System.Linq.IQueryable<TQueryEntity>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(methodInfo, instance, new object[] { query, args });
      }
      else
      {
        result = new global::Sungero.MobileApps.MobileAppSettingEmployeePropertyFilteringServerHandler<TQueryEntity>(sourceEntity).EmployeeFiltering(query, args);
      }
      if (args.DisableUiFiltering)
        global::Sungero.Domain.UiFilteringEventManagementScope.DisableEvent<TQueryEntity>();
      return result;
    }

    public MobileAppSettingFilterForEmployee(string propertyName)
      : base(propertyName)
    {
    }
  }

  public class MobileAppSettingSearchFilterForEmployee<TQueryEntity>
    : global::Sungero.Domain.SearchDialogPropertyFilter<TQueryEntity>
    where TQueryEntity : class, global::Sungero.CoreEntities.IRecipient
  {
    protected override global::System.Linq.IQueryable<TQueryEntity> ApplyAppliedFilter(global::System.Linq.IQueryable<TQueryEntity> query, System.Guid entityType)
    {
      var args = new global::Sungero.Domain.PropertySearchDialogFilteringEventArgs(entityType);
      global::System.Linq.IQueryable<TQueryEntity> result;
      var filterType = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve("Sungero.MobileApps.MobileAppSettingEmployeeSearchPropertyFilteringServerHandler`1");
      if (filterType != null)
      {
        var genericType = filterType.MakeGenericType(typeof(TQueryEntity));
        var instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(genericType);
        var methodInfo = genericType.GetMethod("EmployeeSearchDialogFiltering");
        result = (global::System.Linq.IQueryable<TQueryEntity>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(methodInfo, instance, new object[] { query, args });
      }
      else
      {
        result = new global::Sungero.MobileApps.MobileAppSettingEmployeeSearchPropertyFilteringServerHandler<TQueryEntity>().EmployeeSearchDialogFiltering(query, args);
      }
      if (args.DisableUiFiltering)
          global::Sungero.Domain.UiFilteringEventManagementScope.DisableEvent<TQueryEntity>();
      return result;
    }

    public MobileAppSettingSearchFilterForEmployee(string propertyName)
      : base(propertyName)
    {
    }
  }



  [global::Sungero.Domain.Filter(typeof(global::Sungero.MobileApps.Server.MobileAppSettingFilter<global::Sungero.MobileApps.IMobileAppSetting>))]
  [global::Sungero.Domain.UiFilter(typeof(global::Sungero.MobileApps.Server.MobileAppSettingUiFilter<global::Sungero.MobileApps.IMobileAppSetting>))]
  [global::Sungero.Domain.PropertyFilter(typeof(global::Sungero.MobileApps.Server.MobileAppSettingFilterForEmployee<global::Sungero.Company.IEmployee, global::Sungero.MobileApps.IMobileAppSetting>), "Employee")]
  [global::Sungero.Domain.SearchPropertyFilter(typeof(global::Sungero.MobileApps.Server.MobileAppSettingSearchFilterForEmployee<global::Sungero.CoreEntities.IRecipient>), "Employee")]


  public class MobileAppSetting :
    global::Sungero.CoreEntities.Server.DatabookEntry, global::Sungero.MobileApps.IMobileAppSetting
  {
    public static new readonly global::System.Guid ClassTypeGuid = global::System.Guid.Parse("210b9d5c-0218-43c5-b950-c69a65caec9b");

    public override global::System.Guid TypeGuid
    {
      get { return global::Sungero.MobileApps.Server.MobileAppSetting.ClassTypeGuid; }
    }

    public override string TypeName
    {
      get { return "Sungero.MobileApps.IMobileAppSetting, Sungero.Domain.Interfaces"; }
    }

    public override string DisplayValue
    {
      get { return this.Employee == null ? string.Empty : this.Employee.ToString(); }
      set { throw new global::System.NotSupportedException(global::CommonLibrary.Properties.Resources.SpecifiedPropertyIsNotSupportedFormat("DisplayValue")); }
    }

    public new virtual global::Sungero.MobileApps.IMobileAppSettingState State
    {
      get { return (global::Sungero.MobileApps.IMobileAppSettingState)base.State; }
    }

    protected override global::Sungero.Domain.Shared.IEntityState CreateState()
    {
      return new global::Sungero.MobileApps.Shared.MobileAppSettingState(this);
    }

    public new virtual global::Sungero.MobileApps.IMobileAppSettingInfo Info
    {
      get { return (global::Sungero.MobileApps.IMobileAppSettingInfo)base.Info; }
    }

    public new virtual global::Sungero.MobileApps.IMobileAppSettingAccessRights AccessRights
    {
      get { return (global::Sungero.MobileApps.IMobileAppSettingAccessRights)base.AccessRights; }
    }

    protected override global::Sungero.Domain.Shared.IEntityAccessRights CreateAccessRights()
    {
      return new global::Sungero.MobileApps.Server.MobileAppSettingAccessRights(this);
    }

    protected override global::Sungero.Domain.EntityFunctions CreateServerFunctions()
    {
      return new global::Sungero.MobileApps.Server.MobileAppSettingFunctions(this);
    }

    protected override global::Sungero.Domain.Shared.EntityFunctions CreateSharedFunctions()
    {
      return new global::Sungero.MobileApps.Shared.MobileAppSettingFunctions(this);
    }

    protected override object CreateHandlers() {
      return new global::Sungero.MobileApps.MobileAppSettingServerHandlers(this);
    }

    protected override object CreateSharedHandlers() {
      return new global::Sungero.MobileApps.MobileAppSettingSharedHandlers(this);
    }







    private global::Sungero.Company.IEmployee _Employee;
    public virtual global::Sungero.Company.IEmployee Employee
    {
      get
      {
        return this._Employee;
      }

      set
      {
        this.SetPropertyValue("Employee", this._Employee, value, (propertyValue) => { this._Employee = propertyValue; }, this.EmployeeChangedHandler);
      }
    }


    protected global::Sungero.Domain.Shared.IChildEntityCollection<global::Sungero.MobileApps.IMobileAppSettingVisibleFolders> _VisibleFolders;

    public virtual global::Sungero.Domain.Shared.IChildEntityCollection<global::Sungero.MobileApps.IMobileAppSettingVisibleFolders> VisibleFolders
    {
      get
      {
        if (this._VisibleFolders == null)
        {
          this._VisibleFolders = this.CreateVisibleFoldersCollection();
          this.SetVisibleFoldersEventHandlers();
        }
        return this._VisibleFolders;
      }

      set
      {
        if (this._VisibleFolders != null)
          this.UnsetChildCollectionEventHandlers(this._VisibleFolders);

        this._VisibleFolders = value;
        this.SetVisibleFoldersEventHandlers();
      }
    }

    protected virtual global::Sungero.Domain.Shared.IChildEntityCollection<global::Sungero.MobileApps.IMobileAppSettingVisibleFolders> CreateVisibleFoldersCollection()
    {
      return new global::Sungero.Domain.ChildEntityCollection<global::Sungero.MobileApps.IMobileAppSettingVisibleFolders>() { RootEntity = this };
    }

    private void SetVisibleFoldersEventHandlers()
    {
      this.SetChildCollectionEventHandlers(this._VisibleFolders, "VisibleFolders");

      var changeNotifier = (global::Sungero.Domain.Shared.INotifyChildEntityCollectionChanged)this._VisibleFolders;
      changeNotifier.Added += this.VisibleFoldersAddedHandler;
      changeNotifier.Deleted += this.VisibleFoldersDeletedHandler;
      changeNotifier.Added += this.VisibleFoldersCollectionUpdateEventHandler;
      changeNotifier.Deleted += this.VisibleFoldersCollectionUpdateEventHandler;
      changeNotifier.Updated += this.VisibleFoldersCollectionUpdateEventHandler;
    }

    private void VisibleFoldersCollectionUpdateEventHandler(object sender, global::Sungero.Domain.Shared.BaseChildEntityEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {
      if (this.IsPropertyChangedHandlerEnabled && this.IsPropertyChangedAppliedHandlerEnabled("VisibleFolders"))
        this.VisibleFoldersChangedHandler();
    }



    protected override global::Sungero.Domain.Shared.EntityCreatingFromServerHandler CreateCreatingFromServerHandler(
      global::Sungero.Domain.Shared.IEntity entitySource)
    {
      var instance = Sungero.Metadata.Services.AppliedTypesManager.CreateInstance("Sungero.MobileApps.MobileAppSettingCreatingFromServerHandler", new object[] { (global::Sungero.MobileApps.IMobileAppSetting)entitySource, this.Info });
      if (instance != null)
        return (global::Sungero.Domain.Shared.EntityCreatingFromServerHandler)instance;

      return new global::Sungero.MobileApps.MobileAppSettingCreatingFromServerHandler((global::Sungero.MobileApps.IMobileAppSetting)entitySource, this.Info);
    }

    #region Framework events

    protected void EmployeeChangedHandler()
    {
      var args = new global::Sungero.MobileApps.Shared.MobileAppSettingEmployeeChangedEventArgs(this.State.Properties.Employee, this.Employee, this);
     ((global::Sungero.MobileApps.IMobileAppSettingSharedHandlers)this.SharedHandlers).EmployeeChanged(args);
    }

    protected void VisibleFoldersChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.CollectionPropertyChangedEventArgs(this);
     ((global::Sungero.MobileApps.IMobileAppSettingSharedHandlers)this.SharedHandlers).VisibleFoldersChanged(args);
    }



    protected virtual global::Sungero.MobileApps.MobileAppSettingVisibleFoldersSharedCollectionHandlers CreateVisibleFoldersAddedHandler(global::Sungero.Domain.Shared.ChildEntityAddedEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {
      return new global::Sungero.MobileApps.MobileAppSettingVisibleFoldersSharedCollectionHandlers(this, e.Value, null, e.Source);
    }

    protected virtual global::Sungero.MobileApps.MobileAppSettingVisibleFoldersSharedCollectionHandlers CreateVisibleFoldersDeletedHandler(global::Sungero.Domain.Shared.ChildEntityDeletedEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {
      return new global::Sungero.MobileApps.MobileAppSettingVisibleFoldersSharedCollectionHandlers(this, null, e.Value, null);
    }

    protected virtual void VisibleFoldersAddedHandler(object sender, global::Sungero.Domain.Shared.ChildEntityAddedEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {
      var type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve("Sungero.MobileApps.MobileAppSettingVisibleFoldersSharedCollectionHandlers");
      if (type != null)
      {
        var instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(type, new object[] { this, e.Value, null, e.Source });
        var methodInfo = type.GetMethod("VisibleFoldersAdded");
        var args = new global::Sungero.Domain.Shared.CollectionPropertyAddedEventArgs(this);
        global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(methodInfo, instance, new object[] { args });
      }
      else
      {
        var collectionHandlers = this.CreateVisibleFoldersAddedHandler(e);
        if (collectionHandlers != null)
        {
          var args = new global::Sungero.Domain.Shared.CollectionPropertyAddedEventArgs(this);
          collectionHandlers.VisibleFoldersAdded(args);
        }
      }
    }

    protected virtual void VisibleFoldersDeletedHandler(object sender, global::Sungero.Domain.Shared.ChildEntityDeletedEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {
      var type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve("Sungero.MobileApps.MobileAppSettingVisibleFoldersSharedCollectionHandlers");
      if (type != null)
      {
        var instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(type, new object[] { this, null, e.Value, null });
        var methodInfo = type.GetMethod("VisibleFoldersDeleted");
        var args = new global::Sungero.Domain.Shared.CollectionPropertyDeletedEventArgs(this);
        global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(methodInfo, instance, new object[] { args });
      }
      else
      {
        var collectionHandlers = this.CreateVisibleFoldersDeletedHandler(e);
        if (collectionHandlers != null)
        {
          var args = new global::Sungero.Domain.Shared.CollectionPropertyDeletedEventArgs(this);
          collectionHandlers.VisibleFoldersDeleted(args);
        }
      }
    }


    #endregion


    public MobileAppSetting()
    {
    }

  }
}

// ==================================================================
// MobileAppSettingHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.MobileApps
{
  public partial class MobileAppSettingEmployeePropertyFilteringServerHandler<T>
    : global::Sungero.Domain.EntityPropertyFilteringServerHandler
    where T : class, global::Sungero.Company.IEmployee
  {
    private global::Sungero.MobileApps.IMobileAppSetting _obj
    {
      get { return (global::Sungero.MobileApps.IMobileAppSetting)this.Entity; }
    }

    public virtual global::System.Linq.IQueryable<T> EmployeeFiltering(global::System.Linq.IQueryable<T> query, global::Sungero.Domain.PropertyFilteringEventArgs e)
    {
      return query;
    }

    public MobileAppSettingEmployeePropertyFilteringServerHandler(global::Sungero.MobileApps.IMobileAppSetting entity)
      : base(entity)
    {
    }
  }

  public partial class MobileAppSettingEmployeeSearchPropertyFilteringServerHandler<T>
    : global::Sungero.Domain.SearchPropertyFilteringServerHandler
    where T : class, global::Sungero.CoreEntities.IRecipient
  {

    public virtual global::System.Linq.IQueryable<T> EmployeeSearchDialogFiltering(global::System.Linq.IQueryable<T> query, global::Sungero.Domain.PropertySearchDialogFilteringEventArgs e)
    {
      return query;
    }

    public MobileAppSettingEmployeeSearchPropertyFilteringServerHandler()
      : base()
    {
    }
  }



  public partial class MobileAppSettingFilteringServerHandler<T>
    : global::Sungero.Domain.EntityFilteringServerHandler<T>  
    where T : class, global::Sungero.MobileApps.IMobileAppSetting
  {
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    protected new global::Sungero.MobileApps.IMobileAppSettingFilterState Filter { get; private set; }

    private global::Sungero.MobileApps.IMobileAppSettingFilterState _filter
    {
      get
      {
        return this.Filter;
      }
    }

    public MobileAppSettingFilteringServerHandler(global::Sungero.MobileApps.IMobileAppSettingFilterState filter)
    : base()
    {
      this.Filter = filter;
    }

    protected MobileAppSettingFilteringServerHandler()
    {
    }

    public override global::System.Linq.IQueryable<T> Filtering(global::System.Linq.IQueryable<T> query, global::Sungero.Domain.FilteringEventArgs e)
    {
      return query;
    }


  }

  public partial class MobileAppSettingUiFilteringServerHandler<T>
    : global::Sungero.Domain.EntityUiFilteringServerHandler<T>
    where T : class, global::Sungero.MobileApps.IMobileAppSetting
  {
    public override global::System.Linq.IQueryable<T> Filtering(global::System.Linq.IQueryable<T> query, global::Sungero.Domain.UiFilteringEventArgs e)
    {
      query = base.Filtering(query, e);
            return query;
    }
  }

  public partial class MobileAppSettingSearchDialogServerHandler : global::Sungero.CoreEntities.DatabookEntrySearchDialogServerHandler
   {
     private global::Sungero.MobileApps.Server.MobileAppSettingSearchDialogModel _dialog
     {
       get
       {
         return (global::Sungero.MobileApps.Server.MobileAppSettingSearchDialogModel)this.Dialog;
       }
     }

     public MobileAppSettingSearchDialogServerHandler(global::Sungero.MobileApps.Server.MobileAppSettingSearchDialogModel dialog)
       : base(dialog)
     {
     }
   }

  public partial class MobileAppSettingServerHandlers : global::Sungero.CoreEntities.DatabookEntryServerHandlers
  {
    private global::Sungero.MobileApps.IMobileAppSetting _obj
    {
      get { return (global::Sungero.MobileApps.IMobileAppSetting)this.Entity; }
    }

    public MobileAppSettingServerHandlers(global::Sungero.MobileApps.IMobileAppSetting entity)
      : base(entity)
    {
    }
  }

  public partial class MobileAppSettingCreatingFromServerHandler : global::Sungero.CoreEntities.DatabookEntryCreatingFromServerHandler
  {
    private global::Sungero.MobileApps.IMobileAppSetting _source
    {
      get { return (global::Sungero.MobileApps.IMobileAppSetting)this.Source; }
    }

    private global::Sungero.MobileApps.IMobileAppSettingInfo _info
    {
      get { return (global::Sungero.MobileApps.IMobileAppSettingInfo)this._Info; }
    }

    public MobileAppSettingCreatingFromServerHandler(global::Sungero.MobileApps.IMobileAppSetting source, global::Sungero.MobileApps.IMobileAppSettingInfo info)
      : base(source, info)
    {
    }
  }

}

// ==================================================================
// MobileAppSettingEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.MobileApps.Server
{
}

// ==================================================================
// MobileAppSettingAccessRights.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.MobileApps.Server
{
  public class MobileAppSettingAccessRights : 
    Sungero.CoreEntities.Server.DatabookEntryAccessRights, Sungero.MobileApps.IMobileAppSettingAccessRights
  {

    public MobileAppSettingAccessRights(global::Sungero.Domain.Shared.IEntity entity) : base(entity)
    {
    }
  }

  public class MobileAppSettingTypeAccessRights : 
    Sungero.CoreEntities.Server.DatabookEntryTypeAccessRights, Sungero.MobileApps.IMobileAppSettingAccessRights
  {

    public MobileAppSettingTypeAccessRights(global::System.Type entityType) : base(entityType)
    {
    }
  }
}

// ==================================================================
// MobileAppSettingRepositoryImplementer.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.MobileApps.Server
{
    public class MobileAppSettingRepositoryImplementer<T> : 
      global::Sungero.Domain.RepositoryImplementer<T>,
      global::Sungero.MobileApps.IMobileAppSettingRepositoryImplementer<T>
      where T : global::Sungero.MobileApps.IMobileAppSetting 
    {
       public new global::Sungero.MobileApps.IMobileAppSettingAccessRights AccessRights
       {
          get { return (global::Sungero.MobileApps.IMobileAppSettingAccessRights)base.AccessRights; }
       }

       public new global::Sungero.MobileApps.IMobileAppSettingInfo Info
       {
          get { return (global::Sungero.MobileApps.IMobileAppSettingInfo)base.Info; }
       }

       protected override global::Sungero.Domain.Shared.IEntityAccessRights CreateAccessRights()
       {
         return new global::Sungero.MobileApps.Server.MobileAppSettingTypeAccessRights(typeof(T));
       }
    }
}

// ==================================================================
// MobileAppSettingPanelNavigationFilters.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.MobileApps.Server
{
}

// ==================================================================
// MobileAppSettingServerFunctions.g.cs
// ==================================================================

namespace Sungero.MobileApps.Server
{
  public partial class MobileAppSettingFunctions : global::Sungero.CoreEntities.Server.DatabookEntryFunctions
  {
    private global::Sungero.MobileApps.IMobileAppSetting _obj
    {
      get { return (global::Sungero.MobileApps.IMobileAppSetting)this.Entity; }
    }

    public MobileAppSettingFunctions(global::Sungero.MobileApps.IMobileAppSetting entity) : base(entity) { }
  }
}

// ==================================================================
// MobileAppSettingFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.MobileApps.Functions
{
  internal static class MobileAppSetting
  {
    /// <redirect project="Sungero.MobileApps.Server" type="Sungero.MobileApps.Server.MobileAppSettingFunctions" />
    [global::Sungero.Core.RemoteAttribute(IsPure = true)]
    internal static  void SendMobileAppSettingChanged(global::Sungero.MobileApps.IMobileAppSetting mobileAppSetting)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)mobileAppSetting).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("SendMobileAppSettingChanged", new System.Type[] {  });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.MobileApps.Server" type="Sungero.MobileApps.Server.MobileAppSettingFunctions" />
    [global::Sungero.Core.RemoteAttribute(IsPure = true)]
    internal static  global::System.Boolean IsUnique(global::Sungero.MobileApps.IMobileAppSetting mobileAppSetting)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)mobileAppSetting).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("IsUnique", new System.Type[] {  });
      return (global::System.Boolean)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.MobileApps.Server" type="Sungero.MobileApps.Server.MobileAppSettingFunctions" />
    [global::Sungero.Core.RemoteAttribute(IsPure = true)]
    internal static  global::System.Collections.Generic.List<global::Sungero.MobileApps.Structures.MobileAppSetting.FolderNameWithId> GetFolderNameWithIds(global::Sungero.MobileApps.IMobileAppSetting mobileAppSetting)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)mobileAppSetting).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetFolderNameWithIds", new System.Type[] {  });
      return (global::System.Collections.Generic.List<global::Sungero.MobileApps.Structures.MobileAppSetting.FolderNameWithId>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.MobileApps.Server" type="Sungero.MobileApps.Server.MobileAppSettingFunctions" />
    internal static  global::System.Collections.Generic.List<global::Sungero.MobileApps.Structures.MobileAppSetting.FolderNameWithId> GetFolderNameWithIds(global::Sungero.MobileApps.IMobileAppSetting mobileAppSetting, System.Collections.Generic.Dictionary<global::System.Guid, global::System.Collections.Generic.List<global::Sungero.CoreEntities.IFolderBase>> folderGroups, System.Collections.Generic.Dictionary<global::System.Guid, Sungero.Metadata.SpecialFolderMetadata> specialFolderMetas)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)mobileAppSetting).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetFolderNameWithIds", new System.Type[] { typeof(System.Collections.Generic.Dictionary<global::System.Guid, global::System.Collections.Generic.List<global::Sungero.CoreEntities.IFolderBase>>), typeof(System.Collections.Generic.Dictionary<global::System.Guid, Sungero.Metadata.SpecialFolderMetadata>) });
      return (global::System.Collections.Generic.List<global::Sungero.MobileApps.Structures.MobileAppSetting.FolderNameWithId>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { folderGroups, specialFolderMetas });
    }
    /// <redirect project="Sungero.MobileApps.Server" type="Sungero.MobileApps.Server.MobileAppSettingFunctions" />
    internal static  void UnionFolders(global::Sungero.MobileApps.IMobileAppSetting mobileAppSetting, System.Collections.Generic.Dictionary<global::System.Guid, global::System.Collections.Generic.List<global::Sungero.CoreEntities.IFolderBase>> destination, System.Collections.Generic.Dictionary<global::System.Guid, global::System.Collections.Generic.List<global::Sungero.CoreEntities.IFolderBase>> source)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)mobileAppSetting).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("UnionFolders", new System.Type[] { typeof(System.Collections.Generic.Dictionary<global::System.Guid, global::System.Collections.Generic.List<global::Sungero.CoreEntities.IFolderBase>>), typeof(System.Collections.Generic.Dictionary<global::System.Guid, global::System.Collections.Generic.List<global::Sungero.CoreEntities.IFolderBase>>) });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { destination, source });
    }
    /// <redirect project="Sungero.MobileApps.Server" type="Sungero.MobileApps.Server.MobileAppSettingFunctions" />
    internal static  System.Collections.Generic.Dictionary<global::System.Guid, Sungero.Metadata.SpecialFolderMetadata> GetSpecialFolderMetas(global::Sungero.MobileApps.IMobileAppSetting mobileAppSetting)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)mobileAppSetting).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetSpecialFolderMetas", new System.Type[] {  });
      return (System.Collections.Generic.Dictionary<global::System.Guid, Sungero.Metadata.SpecialFolderMetadata>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.MobileApps.Server" type="Sungero.MobileApps.Server.MobileAppSettingFunctions" />
    internal static  System.Collections.Generic.Dictionary<global::System.Guid, global::System.Collections.Generic.List<global::Sungero.CoreEntities.IFolderBase>> GetFolders(global::Sungero.MobileApps.IMobileAppSetting mobileAppSetting)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)mobileAppSetting).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetFolders", new System.Type[] {  });
      return (System.Collections.Generic.Dictionary<global::System.Guid, global::System.Collections.Generic.List<global::Sungero.CoreEntities.IFolderBase>>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.MobileApps.Server" type="Sungero.MobileApps.Server.MobileAppSettingFunctions" />
    internal static  System.Collections.Generic.Dictionary<global::System.Guid, global::System.Collections.Generic.List<global::Sungero.CoreEntities.IFolderBase>> GetSpecialFolders(global::Sungero.MobileApps.IMobileAppSetting mobileAppSetting, System.Collections.Generic.Dictionary<global::System.Guid, Sungero.Metadata.SpecialFolderMetadata> specialFolderMetas)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)mobileAppSetting).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetSpecialFolders", new System.Type[] { typeof(System.Collections.Generic.Dictionary<global::System.Guid, Sungero.Metadata.SpecialFolderMetadata>) });
      return (System.Collections.Generic.Dictionary<global::System.Guid, global::System.Collections.Generic.List<global::Sungero.CoreEntities.IFolderBase>>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { specialFolderMetas });
    }
    /// <redirect project="Sungero.MobileApps.Server" type="Sungero.MobileApps.Server.MobileAppSettingFunctions" />
    internal static  global::System.Collections.Generic.List<global::System.Nullable<global::System.Guid>> GetEmployeeSpecialFolderGuids(global::Sungero.MobileApps.IMobileAppSetting mobileAppSetting)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)mobileAppSetting).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetEmployeeSpecialFolderGuids", new System.Type[] {  });
      return (global::System.Collections.Generic.List<global::System.Nullable<global::System.Guid>>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.MobileApps.Server" type="Sungero.MobileApps.Server.MobileAppSettingFunctions" />
    internal static  global::System.Collections.Generic.List<global::System.Int64> GetEmployeeSpecialFolderIds(global::Sungero.MobileApps.IMobileAppSetting mobileAppSetting)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)mobileAppSetting).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetEmployeeSpecialFolderIds", new System.Type[] {  });
      return (global::System.Collections.Generic.List<global::System.Int64>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Sungero.MobileApps.Server" type="Sungero.MobileApps.Server.MobileAppSettingFunctions" />
    internal static  global::System.String GetFolderReadableName(global::Sungero.MobileApps.IMobileAppSetting mobileAppSetting, global::Sungero.CoreEntities.IFolderBase folderBase, global::System.Guid parent, System.Collections.Generic.Dictionary<global::System.Guid, Sungero.Metadata.SpecialFolderMetadata> specialFolderMetas)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)mobileAppSetting).FunctionsContainer.ServerFunctions;
      var __funcMethod = __functions.GetType().GetMethod("GetFolderReadableName", new System.Type[] { typeof(global::Sungero.CoreEntities.IFolderBase), typeof(global::System.Guid), typeof(System.Collections.Generic.Dictionary<global::System.Guid, Sungero.Metadata.SpecialFolderMetadata>) });
      return (global::System.String)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] { folderBase, parent, specialFolderMetas });
    }

  }
}

// ==================================================================
// MobileAppSettingServerPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.MobileApps.Server
{
  public class MobileAppSettingServerPublicFunctions : global::Sungero.MobileApps.Server.IMobileAppSettingServerPublicFunctions
  {
  }
}

// ==================================================================
// MobileAppSettingQueries.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.MobileApps.Queries
{
  public class MobileAppSetting
  {
    private static global::Sungero.Domain.SqlQueryResolver resolver = new global::Sungero.Domain.SqlQueryResolver("Sungero.MobileApps.Server.MobileAppSetting.MobileAppSettingQueries.xml", System.Reflection.Assembly.GetExecutingAssembly());
  }
}
