
// ==================================================================
// DepartmentsAssignmentCompletionReportResources.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Shared.Reports.DepartmentsAssignmentCompletionReport
{
  public class DepartmentsAssignmentCompletionReportResources : global::Sungero.Docflow.IDepartmentsAssignmentCompletionReportResources
  {
    public virtual global::CommonLibrary.LocalizedString ReportName
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport) , "ReportName");
      }
    }

    public virtual global::CommonLibrary.LocalizedString ReportNameFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport), "ReportName", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString Period
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport) , "Period");
      }
    }

    public virtual global::CommonLibrary.LocalizedString PeriodFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport), "Period", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString PeriodTo
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport) , "PeriodTo");
      }
    }

    public virtual global::CommonLibrary.LocalizedString PeriodToFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport), "PeriodTo", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString AssignmentCompletion
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport) , "AssignmentCompletion");
      }
    }

    public virtual global::CommonLibrary.LocalizedString AssignmentCompletionFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport), "AssignmentCompletion", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString AssignmentsCount
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport) , "AssignmentsCount");
      }
    }

    public virtual global::CommonLibrary.LocalizedString AssignmentsCountFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport), "AssignmentsCount", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString DepartmentName
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport) , "DepartmentName");
      }
    }

    public virtual global::CommonLibrary.LocalizedString DepartmentNameFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport), "DepartmentName", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString DialogTitle
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport) , "DialogTitle");
      }
    }

    public virtual global::CommonLibrary.LocalizedString DialogTitleFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport), "DialogTitle", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString OverdueAssignmentsCount
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport) , "OverdueAssignmentsCount");
      }
    }

    public virtual global::CommonLibrary.LocalizedString OverdueAssignmentsCountFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport), "OverdueAssignmentsCount", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString ClosedRecord
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport) , "ClosedRecord");
      }
    }

    public virtual global::CommonLibrary.LocalizedString ClosedRecordFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport), "ClosedRecord", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString AffectDisciplineAssignmentsCount
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport) , "AffectDisciplineAssignmentsCount");
      }
    }

    public virtual global::CommonLibrary.LocalizedString AffectDisciplineAssignmentsCountFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport), "AffectDisciplineAssignmentsCount", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString CompletedInTimeAssignmentsCount
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport) , "CompletedInTimeAssignmentsCount");
      }
    }

    public virtual global::CommonLibrary.LocalizedString CompletedInTimeAssignmentsCountFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport), "CompletedInTimeAssignmentsCount", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString BusinessUnitName
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport) , "BusinessUnitName");
      }
    }

    public virtual global::CommonLibrary.LocalizedString BusinessUnitNameFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport), "BusinessUnitName", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString SubDepartmentName
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport) , "SubDepartmentName");
      }
    }

    public virtual global::CommonLibrary.LocalizedString SubDepartmentNameFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.Docflow.IDepartmentsAssignmentCompletionReport), "SubDepartmentName", false, args);
    }

  }
}
