
// ==================================================================
// ProjectTeamMembers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Projects.Client
{
  public class ProjectTeamMembers :
    global::Sungero.Projects.Client.ProjectCoreTeamMembers, global::Sungero.Projects.IProjectTeamMembers
  {
    #region Fields and properties

    public static new readonly global::System.Guid ClassTypeGuid = global::System.Guid.Parse("80cbfc1b-3b72-4df6-b7c6-ceca9b15581b");

    public override global::System.Guid TypeGuid
    {
      get { return global::Sungero.Projects.Client.ProjectTeamMembers.ClassTypeGuid; }
    }

    public override string TypeName
    {
      get { return "Sungero.Projects.IProjectTeamMembers, Sungero.Domain.Interfaces"; }
    }

    public new global::Sungero.Projects.IProjectTeamMembersState State
    {
      get
      {
        return (global::Sungero.Projects.IProjectTeamMembersState)base.State;
      }
    }

    protected override global::Sungero.Domain.Shared.IEntityState CreateState()
    {
      return new global::Sungero.Projects.Shared.ProjectTeamMembersState(this);
    }

    public new global::Sungero.Projects.IProjectTeamMembersInfo Info
    {
      get
      {
        return (global::Sungero.Projects.IProjectTeamMembersInfo)base.Info;
      }
    }










    #endregion

    #region Methods

    #endregion

    #region Framework events





    #endregion

    #region Constructors




    public ProjectTeamMembers()
    {








    }

    #endregion

  }
}
