
// ==================================================================
// ManagersAssistant.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Company.Client
{
  public class ManagersAssistant :
    global::Sungero.Company.Client.ManagersAssistantBase, global::Sungero.Company.IManagersAssistant
  {
    #region Fields and properties

    public static new readonly global::System.Guid ClassTypeGuid = global::System.Guid.Parse("c2200a86-5d5d-47d6-930d-c3ce8b11f04b");

    public override global::System.Guid TypeGuid
    {
      get { return global::Sungero.Company.Client.ManagersAssistant.ClassTypeGuid; }
    }

    public override string TypeName
    {
      get { return "Sungero.Company.IManagersAssistant, Sungero.Domain.Interfaces"; }
    }

      public override string DisplayValue
      {
        get { return this.Manager == null ? string.Empty : this.Manager.ToString(); }
        set { throw new global::System.NotSupportedException(global::CommonLibrary.Properties.Resources.SpecifiedPropertyIsNotSupportedFormat("DisplayValue")); }
      }

      public override string DisplayPropertyName
      {
        get { return "Manager"; }
      }


    public new global::Sungero.Company.IManagersAssistantState State
    {
      get
      {
        return (global::Sungero.Company.IManagersAssistantState)base.State;
      }
    }

    protected override global::Sungero.Domain.Shared.IEntityState CreateState()
    {
      return new global::Sungero.Company.Shared.ManagersAssistantState(this);
    }

    public new global::Sungero.Company.IManagersAssistantInfo Info
    {
      get
      {
        return (global::Sungero.Company.IManagersAssistantInfo)base.Info;
      }
    }

    public new global::Sungero.Company.IManagersAssistantAccessRights AccessRights
    {
      get
      {
        return (global::Sungero.Company.IManagersAssistantAccessRights)base.AccessRights;
      }
    }

    protected override global::Sungero.Domain.Shared.IEntityAccessRights CreateAccessRights()
    {
      return new global::Sungero.Company.Client.ManagersAssistantAccessRights(this);
    }

        protected global::Sungero.Domain.Client.SimpleProperty<global::System.Boolean?> _IsAssistant;

        public virtual global::System.Boolean? IsAssistant
        {
          get { return this._IsAssistant.Value; }
          set { this._IsAssistant.Value = value; }
        }
        protected global::Sungero.Domain.Client.SimpleProperty<global::System.Boolean?> _PreparesAssignmentCompletion;

        public virtual global::System.Boolean? PreparesAssignmentCompletion
        {
          get { return this._PreparesAssignmentCompletion.Value; }
          set { this._PreparesAssignmentCompletion.Value = value; }
        }
        protected global::Sungero.Domain.Client.SimpleProperty<global::System.Boolean?> _SendActionItems;

        public virtual global::System.Boolean? SendActionItems
        {
          get { return this._SendActionItems.Value; }
          set { this._SendActionItems.Value = value; }
        }




              protected global::Sungero.Domain.Client.INavigationProperty<global::Sungero.Company.IEmployee> _Assistant;

              public virtual global::Sungero.Company.IEmployee Assistant
              {
              get
              {
                return this._Assistant.Value as global::Sungero.Company.IEmployee;
              }

              set
              {
                (this._Assistant as global::Sungero.Domain.Client.IProperty).Value = value;
              }
            }










    #endregion

    #region Methods

    protected override object CreateActionsHandlers()
    {
      return new global::Sungero.Company.Client.ManagersAssistantActions(this);
    }

    protected override object CreateCollectionActionsHandlers()
    {
      return new global::Sungero.Company.Client.ManagersAssistantCollectionActions();
    }

    protected override object CreateAnyChildEntityActionsHandlers()
    {
      return new global::Sungero.Company.Client.ManagersAssistantAnyChildEntityActions();
    }

    protected override object CreateAnyChildEntityCollectionActionsHandlers()
    {
      return new global::Sungero.Company.Client.ManagersAssistantAnyChildEntityCollectionActions();
    }


    protected override global::Sungero.Domain.Client.EntityFunctions CreateClientFunctions()
    {
      return new global::Sungero.Company.Client.ManagersAssistantFunctions(this);
    }

    protected override global::Sungero.Domain.Shared.EntityFunctions CreateSharedFunctions()
    {
      return new global::Sungero.Company.Shared.ManagersAssistantFunctions(this);
    }
    protected override object CreateHandlers() {
      return new global::Sungero.Company.ManagersAssistantClientHandlers(this);
    }
    protected override object CreateSharedHandlers() {
      return new global::Sungero.Company.ManagersAssistantSharedHandlers(this);
    }

    #endregion

    #region Framework events

    protected void AssistantChangedHandler()
    {
      var args = new global::Sungero.Company.Shared.ManagersAssistantAssistantChangedEventArgs(this.State.Properties.Assistant, this.Assistant, this);
     ((global::Sungero.Company.IManagersAssistantSharedHandlers)this.SharedHandlers).AssistantChanged(args);
    }

    protected void IsAssistantChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.BooleanPropertyChangedEventArgs(this.State.Properties.IsAssistant, this.IsAssistant, this);
     ((global::Sungero.Company.IManagersAssistantSharedHandlers)this.SharedHandlers).IsAssistantChanged(args);
    }

    protected void PreparesAssignmentCompletionChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.BooleanPropertyChangedEventArgs(this.State.Properties.PreparesAssignmentCompletion, this.PreparesAssignmentCompletion, this);
     ((global::Sungero.Company.IManagersAssistantSharedHandlers)this.SharedHandlers).PreparesAssignmentCompletionChanged(args);
    }

    protected void SendActionItemsChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.BooleanPropertyChangedEventArgs(this.State.Properties.SendActionItems, this.SendActionItems, this);
     ((global::Sungero.Company.IManagersAssistantSharedHandlers)this.SharedHandlers).SendActionItemsChanged(args);
    }



  protected global::Sungero.Company.IEmployee AssistantValueInputHandler(global::Sungero.Company.IEmployee value)
  {
    var args = new global::Sungero.Company.Client.ManagersAssistantAssistantValueInputEventArgs(this.Assistant, value, this, this.Info.Properties.Assistant);
    ((global::Sungero.Company.ManagersAssistantClientHandlers)this.Handlers).AssistantValueInput(args);
    return args.NewValue;
  }

  protected global::System.Boolean? IsAssistantValueInputHandler(global::System.Boolean? value)
  {
    var args = new global::Sungero.Presentation.BooleanValueInputEventArgs(this.IsAssistant, value, this, this.Info.Properties.IsAssistant);
    ((global::Sungero.Company.ManagersAssistantClientHandlers)this.Handlers).IsAssistantValueInput(args);
    return args.NewValue;
  }

  protected global::System.Boolean? PreparesAssignmentCompletionValueInputHandler(global::System.Boolean? value)
  {
    var args = new global::Sungero.Presentation.BooleanValueInputEventArgs(this.PreparesAssignmentCompletion, value, this, this.Info.Properties.PreparesAssignmentCompletion);
    ((global::Sungero.Company.ManagersAssistantClientHandlers)this.Handlers).PreparesAssignmentCompletionValueInput(args);
    return args.NewValue;
  }

  protected global::System.Boolean? SendActionItemsValueInputHandler(global::System.Boolean? value)
  {
    var args = new global::Sungero.Presentation.BooleanValueInputEventArgs(this.SendActionItems, value, this, this.Info.Properties.SendActionItems);
    ((global::Sungero.Company.ManagersAssistantClientHandlers)this.Handlers).SendActionItemsValueInput(args);
    return args.NewValue;
  }



    #endregion

    #region Constructors




              protected virtual void InitAssistantNavigationProperty()
              {
                this._Assistant = new global::Sungero.Domain.Client.NavigationProperty<global::Sungero.Company.IEmployee>("Assistant", this);
                this._Assistant.ValueChanged += (sender, e) => { this.AssistantChangedHandler(); };
                this.AddProperty(this._Assistant as global::Sungero.Domain.Client.IProperty);
              }




    public ManagersAssistant()
    {
            this._IsAssistant = new global::Sungero.Domain.Client.SimpleProperty<global::System.Boolean?>("IsAssistant", this);
            this._IsAssistant.ValueChanged += (sender, e) => { this.IsAssistantChangedHandler(); };
            this.AddProperty(this._IsAssistant);

            this._PreparesAssignmentCompletion = new global::Sungero.Domain.Client.SimpleProperty<global::System.Boolean?>("PreparesAssignmentCompletion", this);
            this._PreparesAssignmentCompletion.ValueChanged += (sender, e) => { this.PreparesAssignmentCompletionChangedHandler(); };
            this.AddProperty(this._PreparesAssignmentCompletion);

            this._SendActionItems = new global::Sungero.Domain.Client.SimpleProperty<global::System.Boolean?>("SendActionItems", this);
            this._SendActionItems.ValueChanged += (sender, e) => { this.SendActionItemsChangedHandler(); };
            this.AddProperty(this._SendActionItems);

            this.InitAssistantNavigationProperty();








    }

    #endregion

  }
}

// ==================================================================
// ManagersAssistantPresenter.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Company.Client
{
  public class ManagersAssistantPresenter<T> :
    global::Sungero.Company.Client.ManagersAssistantBasePresenter<T>
    where T : class, global::Sungero.Company.IManagersAssistant
  {
    #region Fields and properties




    #endregion

    #region Methods


    #endregion

    #region Framework events

    protected override void EntityPropertyChangedEventHandler(object sender, global::System.ComponentModel.PropertyChangedEventArgs e)
    {
      base.EntityPropertyChangedEventHandler(sender, e);
    }

    #endregion

              protected global::Sungero.Domain.Client.IEntityCollectionPresenter _AssistantCollectionPresenter;
              public global::Sungero.Domain.Client.IEntityCollectionPresenter AssistantCollectionPresenter
              {
          get { return this._AssistantCollectionPresenter; }
        }



    #region Constructors

    private void Init()
    {
              this._ManagerCollectionPresenter
              .Query = global::Sungero.Domain.Client.Session.GetValuesForNavigationPropertyWithoutSourceEntity<global::Sungero.Company.IEmployee>(() => this.Entity.Id, typeof(T), "Manager");

                  this._AssistantCollectionPresenter = this.CreateCollectionPresenterForNavigationProperty<global::Sungero.Company.IEmployee>(global::System.Guid.Parse("6f98c890-c53f-48ef-a78b-ecd83c4c827d"));
              this._AssistantCollectionPresenter
              .Query = global::Sungero.Domain.Client.Session.GetValuesForNavigationPropertyWithoutSourceEntity<global::Sungero.Company.IEmployee>(() => this.Entity.Id, typeof(T), "Assistant");


    }

    public ManagersAssistantPresenter()
    {
      this.Init();
    }

    #endregion
  }
}

// ==================================================================
// ManagersAssistantCollectionPresenter.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Company.Client
{
  public class ManagersAssistantCollectionPresenter<T> : 
    global::Sungero.Company.Client.ManagersAssistantBaseCollectionPresenter<T>
    where T: class, global::Sungero.Company.IManagersAssistant
  {
    #region Actions



    #endregion

    #region Methods


    #endregion

    public ManagersAssistantCollectionPresenter(global::System.Linq.IQueryable<T> query, OnLookup onLookup)
      : base(query, onLookup)
    {
    }

    public ManagersAssistantCollectionPresenter(global::System.Linq.IQueryable<T> query)
      : this(query, null) { }

    public ManagersAssistantCollectionPresenter(OnLookup onLookup)
      : this(null, onLookup) { }

    public ManagersAssistantCollectionPresenter()
      : this(null, null) { }
  }
}

// ==================================================================
// ManagersAssistantRepositoryImplementer.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Company.Client
{ 
  public class ManagersAssistantRepositoryImplementer<T> : 
      global::Sungero.Company.Client.ManagersAssistantBaseRepositoryImplementer<T>,
      global::Sungero.Company.IManagersAssistantRepositoryImplementer<T>
      where T : global::Sungero.Company.IManagersAssistant
    {
       public new global::Sungero.Company.IManagersAssistantAccessRights AccessRights
       {
          get { return (global::Sungero.Company.IManagersAssistantAccessRights)base.AccessRights; }
       }

       public new global::Sungero.Company.IManagersAssistantInfo Info
       {
          get { return (global::Sungero.Company.IManagersAssistantInfo)base.Info; }
       }

       protected override global::Sungero.Domain.Shared.IEntityAccessRights CreateAccessRights()
       {
         return new global::Sungero.Company.Client.ManagersAssistantTypeAccessRights(typeof(T));
       }
    }
}

// ==================================================================
// ManagersAssistantAccessRights.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Company.Client
{
  public class ManagersAssistantAccessRights : 
    Sungero.Company.Client.ManagersAssistantBaseAccessRights, Sungero.Company.IManagersAssistantAccessRights
  {

    public ManagersAssistantAccessRights(global::Sungero.Domain.Shared.IEntity entity) : base(entity)
    {
    }
  }

  public class ManagersAssistantTypeAccessRights : 
    Sungero.Company.Client.ManagersAssistantBaseTypeAccessRights, Sungero.Company.IManagersAssistantAccessRights
  {

    public ManagersAssistantTypeAccessRights(global::System.Type entityType) : base(entityType)
    {
    }
  }
}
