
// ==================================================================
// ModuleFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.FinancialArchiveUI.Functions
{
  internal static partial class Module
  {
    /// <redirect project="Sungero.FinancialArchiveUI.ClientBase" type="Sungero.FinancialArchiveUI.Client.ModuleFunctions" />
    internal static void ImportAndShowDocumentFromFile()
    {
      var __moduleId = new global::System.Guid("e99ae7e2-edb7-4904-a19a-4577f07609a4");
      var __finalModuleMetadatda = global::Sungero.Metadata.MetadataExtension.GetFinal(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(__moduleId) ?? global::Sungero.Metadata.Services.MetadataSearcher.FindLayerModuleMetadata(__moduleId));
      var __funcNamespace = "ClientBase" == "ClientBase" ? __finalModuleMetadatda.ClientNamespace : __finalModuleMetadatda.ClientBaseNamespace;
      var __typeName = __funcNamespace + ".ModuleFunctions, Sungero.FinancialArchiveUI.ClientBase";
      var __type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve(__typeName);
      if (__type != null)
      {
        var __instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(__type);
        var __methodInfo = __type.GetMethod("ImportAndShowDocumentFromFile", global::System.Array.Empty<global::System.Type>());
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__methodInfo, __instance, null);
      }
      else
      {
    ((global::Sungero.FinancialArchiveUI.Client.ModuleFunctions)GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType.ClientBase, __finalModuleMetadatda)).ImportAndShowDocumentFromFile();
      }
    }
    /// <redirect project="Sungero.FinancialArchiveUI.ClientBase" type="Sungero.FinancialArchiveUI.Client.ModuleFunctions" />
    internal static void SearchByRequisites()
    {
      var __moduleId = new global::System.Guid("e99ae7e2-edb7-4904-a19a-4577f07609a4");
      var __finalModuleMetadatda = global::Sungero.Metadata.MetadataExtension.GetFinal(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(__moduleId) ?? global::Sungero.Metadata.Services.MetadataSearcher.FindLayerModuleMetadata(__moduleId));
      var __funcNamespace = "ClientBase" == "ClientBase" ? __finalModuleMetadatda.ClientNamespace : __finalModuleMetadatda.ClientBaseNamespace;
      var __typeName = __funcNamespace + ".ModuleFunctions, Sungero.FinancialArchiveUI.ClientBase";
      var __type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve(__typeName);
      if (__type != null)
      {
        var __instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(__type);
        var __methodInfo = __type.GetMethod("SearchByRequisites", global::System.Array.Empty<global::System.Type>());
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__methodInfo, __instance, null);
      }
      else
      {
    ((global::Sungero.FinancialArchiveUI.Client.ModuleFunctions)GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType.ClientBase, __finalModuleMetadatda)).SearchByRequisites();
      }
    }
    /// <redirect project="Sungero.FinancialArchiveUI.ClientBase" type="Sungero.FinancialArchiveUI.Client.ModuleFunctions" />
    internal static void SearchByRequisitesAndExport()
    {
      var __moduleId = new global::System.Guid("e99ae7e2-edb7-4904-a19a-4577f07609a4");
      var __finalModuleMetadatda = global::Sungero.Metadata.MetadataExtension.GetFinal(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(__moduleId) ?? global::Sungero.Metadata.Services.MetadataSearcher.FindLayerModuleMetadata(__moduleId));
      var __funcNamespace = "ClientBase" == "ClientBase" ? __finalModuleMetadatda.ClientNamespace : __finalModuleMetadatda.ClientBaseNamespace;
      var __typeName = __funcNamespace + ".ModuleFunctions, Sungero.FinancialArchiveUI.ClientBase";
      var __type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve(__typeName);
      if (__type != null)
      {
        var __instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(__type);
        var __methodInfo = __type.GetMethod("SearchByRequisitesAndExport", global::System.Array.Empty<global::System.Type>());
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__methodInfo, __instance, null);
      }
      else
      {
    ((global::Sungero.FinancialArchiveUI.Client.ModuleFunctions)GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType.ClientBase, __finalModuleMetadatda)).SearchByRequisitesAndExport();
      }
    }
    /// <redirect project="Sungero.FinancialArchiveUI.ClientBase" type="Sungero.FinancialArchiveUI.Client.ModuleFunctions" />
    internal static void CreateFinancialDocument()
    {
      var __moduleId = new global::System.Guid("e99ae7e2-edb7-4904-a19a-4577f07609a4");
      var __finalModuleMetadatda = global::Sungero.Metadata.MetadataExtension.GetFinal(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(__moduleId) ?? global::Sungero.Metadata.Services.MetadataSearcher.FindLayerModuleMetadata(__moduleId));
      var __funcNamespace = "ClientBase" == "ClientBase" ? __finalModuleMetadatda.ClientNamespace : __finalModuleMetadatda.ClientBaseNamespace;
      var __typeName = __funcNamespace + ".ModuleFunctions, Sungero.FinancialArchiveUI.ClientBase";
      var __type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve(__typeName);
      if (__type != null)
      {
        var __instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(__type);
        var __methodInfo = __type.GetMethod("CreateFinancialDocument", global::System.Array.Empty<global::System.Type>());
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__methodInfo, __instance, null);
      }
      else
      {
    ((global::Sungero.FinancialArchiveUI.Client.ModuleFunctions)GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType.ClientBase, __finalModuleMetadatda)).CreateFinancialDocument();
      }
    }

    private static object GetFunctionsContainer()
    {
      return new global::Sungero.FinancialArchiveUI.Client.ModuleFunctions();
    }

    private static object GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType projectType, global::Sungero.Metadata.ModuleMetadata finalModuleMetadatda)
    {
      var assemblyName = finalModuleMetadatda.GetAssemblyName(projectType);
      var moduleFunctionsType = global::System.Type.GetType(global::System.String.Format("{0}.{1}, {2}", finalModuleMetadatda.FunctionNamespace, "Module", assemblyName));
      var methodInfo = moduleFunctionsType.GetMethod("GetFunctionsContainer", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Static);
      return global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(methodInfo, null, null);
    }
  }
}

// ==================================================================
// ModuleClientPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.FinancialArchiveUI.Client
{
  public partial class ModuleClientPublicFunctions : global::Sungero.FinancialArchiveUI.Client.IModuleClientPublicFunctions
  {
  }
}

// ==================================================================
// ModuleWidgetHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.FinancialArchiveUI.Client
{
}

// ==================================================================
// ModuleHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.FinancialArchiveUI.Client
{

  public partial class FinContractListFolderHandlers
  {
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    protected global::Sungero.FinancialArchiveUI.FolderFilterState.IFinContractListFilterState Filter { get; private set; }

    private global::Sungero.FinancialArchiveUI.FolderFilterState.IFinContractListFilterState _filter
    {
      get
      {
        return this.Filter;
      }
    }

    public virtual void FinContractListValidateFilterPanel(global:: Sungero.Domain.Client.ValidateFilterPanelEventArgs e)
    {
    }

    public FinContractListFolderHandlers(global::Sungero.FinancialArchiveUI.FolderFilterState.IFinContractListFilterState filter)
    {
      this.Filter = filter;
    }

  }

  public partial class DocumentsWithoutScanFolderHandlers
  {
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    protected global::Sungero.FinancialArchiveUI.FolderFilterState.IDocumentsWithoutScanFilterState Filter { get; private set; }

    private global::Sungero.FinancialArchiveUI.FolderFilterState.IDocumentsWithoutScanFilterState _filter
    {
      get
      {
        return this.Filter;
      }
    }

    public virtual void DocumentsWithoutScanValidateFilterPanel(global:: Sungero.Domain.Client.ValidateFilterPanelEventArgs e)
    {
    }

    public DocumentsWithoutScanFolderHandlers(global::Sungero.FinancialArchiveUI.FolderFilterState.IDocumentsWithoutScanFilterState filter)
    {
      this.Filter = filter;
    }

  }

  public partial class SignAwaitedDocumentsFolderHandlers
  {
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    protected global::Sungero.FinancialArchiveUI.FolderFilterState.ISignAwaitedDocumentsFilterState Filter { get; private set; }

    private global::Sungero.FinancialArchiveUI.FolderFilterState.ISignAwaitedDocumentsFilterState _filter
    {
      get
      {
        return this.Filter;
      }
    }

    public virtual void SignAwaitedDocumentsValidateFilterPanel(global:: Sungero.Domain.Client.ValidateFilterPanelEventArgs e)
    {
    }

    public SignAwaitedDocumentsFolderHandlers(global::Sungero.FinancialArchiveUI.FolderFilterState.ISignAwaitedDocumentsFilterState filter)
    {
      this.Filter = filter;
    }

  }

  public partial class PowerOfAttorneyListFolderHandlers
  {
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    protected global::Sungero.FinancialArchiveUI.FolderFilterState.IPowerOfAttorneyListFilterState Filter { get; private set; }

    private global::Sungero.FinancialArchiveUI.FolderFilterState.IPowerOfAttorneyListFilterState _filter
    {
      get
      {
        return this.Filter;
      }
    }

    public virtual void PowerOfAttorneyListValidateFilterPanel(global:: Sungero.Domain.Client.ValidateFilterPanelEventArgs e)
    {
    }

    public PowerOfAttorneyListFolderHandlers(global::Sungero.FinancialArchiveUI.FolderFilterState.IPowerOfAttorneyListFilterState filter)
    {
      this.Filter = filter;
    }

  }

}

